### ISSUE TITLE
npm i oracledb fails with 404

### ISSUE THREAD

**Issue by danylo-bondarenko** [oracle/node-oracledb#1011]
### For general questions:

```
> oracledb@2.2.0 install .\node_modules\oracledb
> node package/oracledbinstall.js

oracledb Beginning installation
oracledb Verifying installation
oracledb Continuing installation
oracledb ERR! NJS-054: Binary build/Release/oracledb.node was not installed.
oracledb ERR! Pre-built binary packages are not available for this version of Node.js (NODE_MODULE_VERSION="64")
oracledb ERR! Failed to install binary package oracledb-v2.2.0-node-v64-win32-x64.gz
oracledb ERR! Error: HTTPS request for https://github.com/oracle/node-oracledb/releases/download/v2.2.0/oracledb-v2.2.0-node-v64-win32-x64.gz failed with code 404
oracledb ERR! For help see https://oracle.github.io/node-oracledb/INSTALL.html#troubleshooting

npm ERR! code ELIFECYCLE
npm ERR! errno 87
npm ERR! oracledb@2.2.0 install: `node package/oracledbinstall.js`
npm ERR! Exit status 87
npm ERR!
npm ERR! Failed at the oracledb@2.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by cjbj** [comment]
Upgrade to node-oracledb 3.0.1.

The available binary packages for each node-oracledb version are shown at https://github.com/oracle/node-oracledb/releases.  Version 2.2 had pre-built binaries for Node.js versions with ABIs 46, 48, 57 and 59. The mapping between ABI numbers and Node.js versions is shown on https://nodejs.org/en/download/releases/.  The first node-oracledb release that supported ABI 64 / Node.js 6 was node-oracledb 2.3.

**Comment by Barathwaja** [comment]
@cjbj Its still not working

**Comment by cjbj** [comment]
That shows you have is32 architecture; sorry we don't have prebuilt binaries for that.  Here are the instructions for building from source code that you need to follow: https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#github  
Read them carefully and make sure you have all the pre-requisites.

The error messages will be a [little clearer in the next release](https://github.com/oracle/node-oracledb/blob/master/package/install.js#L67).

PS it's more helpful to cut & paste logs instead of giving a screenshot.
