### ISSUE TITLE
@Types/oracledb out of sync

### ISSUE THREAD

**Issue by prichmp** [oracle/node-oracledb#1024]
It seems that the Typescript definition files are not accurate to the latest oracledb. 

For example: 

In `oracledb.createPool(poolAttributes: IPoolAttributes): IPromise< IConnectionPool >;` IPoolAttributes is missing `poolPingInterval` and `_enableStats`.
IConnectionPool is missing `_logStats()`. 

There are probably other missing keys as well.

I'm using @types/oracledb 1.11.34 and oracledb 3.0.1

**Comment by cjbj** [comment]
The Typescript definitions are not part of the core node-oracledb project (aka we still have lower level features to work on).  Maybe you can submit updates?

**Comment by dmcghan** [comment]
Pinging @Bigous https://github.com/oracle/node-oracledb/issues/169 👀

**Comment by andreasmarkussen** [comment]
@dmcghan - create an issue or a PR on https://github.com/DefinitelyTyped/DefinitelyTyped

For PR inspiration see:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11808

**Comment by danilohgds** [comment]
@andreasmarkussen feel free to submit a PR for this. As mentioned earlier Typescript definitions are not part of the core, thus low-priority :).

**Comment by Bigous** [comment]
After typescript 2.2 do we really need to use the typescript definitions (of course it's better because it's more concise than the inferred one). Typescript is now inferring the definitions with only the JS dependency and if the JS is well documented with the appropriate JSDocs tags, it does a pretty good job. Not as good as a human written definition, but at least you don't need to update the definition file each time a version is release.

**Comment by dmcghan** [comment]
@Bigous Does this mean we need to use JSDocs tags? 😅
