### ISSUE TITLE
ORA-12560: TNS:protocol adapter error

### ISSUE THREAD

**Issue by TiaraH** [oracle/node-oracledb#1058]
I installed nodejs+oracledb+oracle instant client+VS in my windows 10, the version is matched,
but when I connect to remote oracle server I got this error code: ORA-12560
here is the PATH setting:

OCI_INC_DIR=C:\www\instantclient_12_2\sdk\include
OCI_LIB_DIR=C:\www\instantclient_12_2\sdk\lib
PATH=%PATH%;C:\www\instantclient_18_3\vc14C;\www\instantclient_18_3
TNS_ADMIN=C:\www\instantclient_18_3\network\admin

**Comment by cjbj** [comment]
- please share the code that fails with us, and what's in your network configuration files.

- you don't need OCI_INC_DIR, OCI_LIB_DIR variables (they were needed with node-oracledb V1 only)

- you don't need TNS_ADMIN set, since the directory you set it to is already a default directory for configuration files

**Comment by TiaraH** [comment]
Hi cjbj,
I tried to copy the same code to another files, and it's worked.  Still no idea where goes wrong, but it's solved, thanks.
