### ISSUE TITLE
Installation does not build from source automatically

### ISSUE THREAD

**Issue by jrasm91** [oracle/node-oracledb#1076]
Installation without internet access should automatically try to build from source, but does not.

**Comment by danilohgds** [comment]
@jrasm91 I understand that this might be a feature request, am I correct? 

There are specific procedures on how to install and build from source when u have no internet access.  Also note that the documentation: https://oracle.github.io/node-oracledb/INSTALL.html#offline does not mention that the module will be automatically built.

@cjbj should this be a feature?

**Comment by jrasm91** [comment]
Yeah, I suppose this should be a feature request. The support for offline support is pretty limited and basically makes the library unusable (or really difficult) in a corporate environment.

I ran into a similar problem with the node-sass library, but they had added several options to work around the issue, one of which was building from source. The others included passing in parameters to use local cached copies of the bindings instead (see [here](https://github.com/sass/node-sass#binary-configuration-parameters)).

Either of these options would significantly increase the usability / ease of this module, especially in a corporate environment.

**Comment by cjbj** [comment]
There are no plans for a fallback-to-auto-build capability if `npm install oracledb` can't find a suitable binary.  This would add a bunch of untrustable 3rd party dependencies into the installation process, and greatly complicate things.  The installation manual [Node-oracledb Installation from Source Code](https://oracle.github.io/node-oracledb/INSTALL.html#github) as mentioned by @danilohgds  has clear instructions for installing from source code.  You can use either github or oss.oracle.com to get the source.  For example, just change your package.json to depend on `oracle/node-oracledb#v3.1.2` instead of `oracledb`.

Most corporations are using Linux or Windows, for which we have pre-built binaries on npm.

You can also easily host binaries in a corporate network, see  [Building and Hosting your own node-oracledb Packages](https://oracle.github.io/node-oracledb/INSTALL.html#selfhost).
