### ISSUE TITLE
Case Insensitive Sorting using SODA

### ISSUE THREAD

**Issue by charleaux** [oracle/node-oracledb#1099]
I'd like to know if it's possible to do case insensitive sorting using the SODA api

**Comment by cjbj** [comment]
I recall some email on the topic but will let @morgiyan answer.

**Comment by morgiyan** [comment]
Unfortunately not at the moment, but looks like it can be supported (the underlying SQL support is there). 

We'd need to provide such support in both the $orderby and the index specs (at least in basic cases the orderby can efficiently run off the index, so if we're going to add a case-insensitive orderby we need to be able to declare a case insensitive index as well. Such an index would then be usable for running the case-insensitive orderby).

Couple of questions, so that we can prioritize this wrt other items we're working on:

* Do you need this for production or are you just exploring?
* Do you have a date by which you'd need this?

Btw, for quicker turn-around on SODA questions, please feel free to add @morgiyan to the post. Then I'll get a notificiation. I just saw this question now, since @cjbj tagged me in his reply.

Thanks.

**Comment by charleaux** [comment]
@morgiyan 

I ended up doing this:

    let pageNumber = req.query.pageNumber ? +req.query.pageNumber : 0;
    let pageSize = req.query.pageSize ? +req.query.pageSize : 0;
    let searchFilter =
      '%' +
      (req.query.searchFilter ? req.query.searchFilter.toUpperCase() : '') +
      '%';
    let pageOffset = pageNumber * pageSize;
    let filter = {
      $or: [
        { username: { $upper: { $like: searchFilter } } },
        { displayName: { $upper: { $like: searchFilter } } }
      ]
    };

    let results = await collection
      .find()
      .skip(pageOffset)
      .limit(pageSize)
      .filter(filter)
      .getDocuments();


But based on your response I realize it's probably not such a good idea because the index issue which I didn't consider.

**Comment by morgiyan** [comment]
Right. It will work fine, but it will not pickup the index. 

I looked more into adding support for "upper" and "lower" to SODA indexes, so that they can be picked up by QBEs that involve $upper and $lower. It's not difficult to enhance SODA to support this, but It turns out there's an underlying SQL enhancement that's required. We need [json_value](https://docs.oracle.com/en/database/oracle/oracle-database/19/adjsn/function-JSON_VALUE.html#GUID-0565F0EE-5F13-44DD-8321-2AC142959215) to support upper/lower[ item methods](https://docs.oracle.com/en/database/oracle/oracle-database/19/adjsn/json-path-expressions.html#GUID-8656CAB9-C293-4A99-BB62-F38F3CFC4C13). We are looking into whether that's doable. I'll reply here once we know for sure. This would benefit both SODA users, as well as direct Oracle SQL/JSON users (since they also don't currently have a way to declare an index with "upper" or "lower" on a JSON field).

In the meantime, could you work around this issue by converting userName and displayName into upper case prior to insertion of the document? i.e. each document would contain both the original case-sensitive name and it's upper-cased version:

{"userName" : "charles", "userNameUpper" : "CHARLES", ... }

Then your QBE can use the upper-cased field (e.g. "userNameUpper" in this example), without the "$upper" item method. And then index can be declared using that field as well:

createIndex({"name" : "myidx", "fields" : [ {"path" : "userNameUpper"}]})

I realize doing this kind of pre-processing on the document is not ideal, but maybe OK as a workaround?

Also: if your "$like" value starts with the wildcard, e.g. {$like : "%something"}, that will not pickup a B-tree index. That's true for relational data/indexing as well. It's covered, for example [here](https://use-the-index-luke.com/sql/where-clause/searching-for-ranges/like-performance-tuning)). In order to be picked up by the index, the "$like" value should not start with the wildcard. For example, {$like : "something%"} can pickup the index.

**Comment by morgiyan** [comment]
@charleaux I talked to our SQL/JSON folks, and we plan to add upper() and lower() support for json_value, which would be needed to add upper/lower support to SODA indexes. But this change would need to be backported, in order for you to be able to use it. So the next thing I need to check on is whether the backport is feasible... would you need this backported to 18c or 19c?

**Comment by charleaux** [comment]
I'm on 18c for now but have plans to migrate to 19c soon (probably within the coming weeks) since it's the terminal release with the best hope for longer term support. 

But that said I don't want to be selfish, you should do what is best from a support perspective.

**Comment by morgiyan** [comment]
@charleaux 

Right, the recommendation is to upgrade to 19c. We'll target backporting to 19c asap then, and also make the SODA-level change to support this. Will let you know when it's available. If you have some deadline for this, let me know and we can connect by email and discuss getting it out in time for that.
