### ISSUE TITLE
Unable to connect to oracle database from node js using sqlnet.ora with oracle wallet

### ISSUE THREAD

**Issue by saiharika213** [oracle/node-oracledb#1109]
Describe exactly what you did and what you want to happen.
I am trying to connect to oracle database(12.1) using node oracledb. Getting below error:
ORA-28759: failure to open file

The database i am trying to connect is connecting using TCPS protocol so to connect to a database either i need to use a JDBC connection string which uses certificates (stored in Java Key stores) to connect. Or using tnsnames.ora and sqlnet.ora file for connecting using oracle wallet.
I am able to connect to another database which is not strictly using TCPS protocol. 
When i ran a connection script i was able to get a success response but not for the above.

Installed instantclient_12_2 to /opt/oracle 
set  
ORACLE_HOME = /opt/oracle/instantclient_12_2
DYLD_LIBRARY_PATH =/opt/oracle/instantclient_12_2
TNS_ADMIN =/opt/oracle/instantclient_12_2
tnsnames.ora and sqlnet.ora file both are placed in opt/oracle/instantclient_12_2

1. What is your Node.js version: use `console.log(process.version)`?  Is it 64-bit or 32-bit: use `console.log(process.arch)`?
v11.9.0

2. What is your node-oracledb version: use `console.log(oracledb.versionString)`?
3.1.2

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

4. What error(s) you are seeing?
ORA-28759: failure to open file

5. What OS (and version) is Node.js executing on: use `console.log(process.platform)`?
darwin

6. What is your Oracle client (e.g. Instant Client) version: use `console.log(oracledb.oracleClientVersionString)`?  Is it 64-bit or 32-bit?  How was it installed?  Where is it installed?
12.2.0.1.0

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?
macOS
files: 
libclntsh.dylib.12.1,libclntshcore.dylib.12.1,libnnz12.dylib,libociei.dylib,libons.dylib
Symbolic link file:
libclntsh.dylib

9. What Oracle environment variables did you set?  How *exactly* did you set them?
ORACLE_HOME = /opt/oracle/instantclient_12_2
DYLD_LIBRARY_PATH =/opt/oracle/instantclient_12_2
TNS_ADMIN =/opt/oracle/instantclient_12_2

10. Do you have a small, single Node.js script that immediately runs to show us the problem?

**Comment by dmcghan** [comment]
Where are your wallet files?

When I get `Error: ORA-28759: failure to open file`, it's typically because I didn't update the directory in the sqlnet.ora file to point to the wallet files correctly. 

If you look in that file, you should see a "DIRECTORY="/path/to/wallet". Do you have that? If so, is it set correctly? It often needs to point to the same directory as where the sqlnet.ora is (`/opt/oracle/instantclient_12_2` in your case) provided that's where the wallet files are.

**Comment by cjbj** [comment]
A couple of comments:
- you can't use Java JDBC connection strings in applications like node-oracledb that use Oracle's C API.  See https://oracle.github.io/node-oracledb/doc/api.html#notjdbc
- Since you are using Instant Client you would never set `ORACLE_HOME`
- If you are using any half-recent macOS you wouldn't set `DYLD_LIBRARY_PATH`, since Apple hobbled it a few versions ago.  The files in `~/lib` will be used so you can unset `DYLD_LIBRARY_PATH`.  Neither `ORACLE_HOME` or `DYLD_LIBRARY_PATH` are mentioned in https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instosx
- Instant Client 18.1 is available for macOS and will connect to Oracle DB 11.2 or later.
- You could (but this is trivial) avoid the need to set `TNS_ADMIN` by putting your *.ora files in the default location `/opt/oracle/instantclient_12_2/network/admin`.  In fact, with Instant Client 18, this subdirectory is created ready for you to use.  A `?` in a sqlnet.ora path maps to the top level Instant Client directory.  So your `WALLET_LOCATION` line in sqlnet.ora can simply be `WALLET_LOCATION = (SOURCE=(METHOD=FILE)(METHOD_DATA=(DIRECTORY="?/network/admin")))` which seems to be the default entry in a number of sqlnet.ora files I've seen recently.
- your problem is 'nothing to do' with node-oracledb, since it is an issue with your network and network file configuration. What this means is that other Oracle forums may have advice that will help you, if we can't answer your questions.

**Comment by saiharika213** [comment]
> Where are your wallet files?
> 
> When I get `Error: ORA-28759: failure to open file`, it's typically because I didn't update the directory in the sqlnet.ora file to point to the wallet files correctly.
> 
> If you look in that file, you should see a "DIRECTORY="/path/to/wallet". Do you have that? If so, is it set correctly? It often needs to point to the same directory as where the sqlnet.ora is (`/opt/oracle/instantclient_12_2` in your case) provided that's where the wallet files are.

DIRECTORY='/opt/oracle/instantclient_12_2/app/wallet' is set with wallets path. But still i get the same error.

**Comment by cjbj** [comment]
@saiharika213 you haven't given us enough detail.

**Comment by saiharika213** [comment]
Issue got resolved by changing the connection string to point the wallet location.

**Comment by dmcghan** [comment]
@saiharika213 Interesting. Do you mean in the tnsnames.ora? Could you give us an example, it may help people with similar issues in the future...

**Comment by rishikesh12** [comment]
@saiharika213 Facing the same issue would be helpful if you could explain in detail the fix that worked for you

**Comment by saiharika213** [comment]
Move the wallets to respective project folder and modify the connection string as below .
Provide the wallet path from root till wallet folder.
 connectString:"(DESCRIPTION = (ADDRESS = (PROTOCOL = TCPS)(HOST = Hostname )(PORT = XXXX))(CONNECT_DATA = (SERVER = DEDICATED)(SERVICE_NAME = Servicename))

**(SECURITY=(MY_WALLET_DIRECTORY=/Users/yharika/Node_Projects/invoice_app/config/wallet))**

)",

**Comment by rishikesh12** [comment]
@saiharika213 does the database you are trying to connect to have SSL_CLIENT_AUTHENTICATION enabled.
If  SSL_CLIENT_AUTHENTICATION  is disabled do we still need to create a client wallet and provide it in the connectString

**Comment by saiharika213** [comment]
@rishikesh12, not sure wheather  the database i am trying to connect is SSL_CLIENT_AUTHENTICATION enabled or not. But the connection protocol was TCPS enabled and had a firewall protected so to connect to it was through the cretificates or the wallet keys provided by DBA.

**Comment by pmrubenrao** [comment]
> Issue got resolved by changing the connection string to point the wallet location.

Can you share your connectionString here.
