### ISSUE TITLE
Result Set from a procedure- alternatives?

### ISSUE THREAD

**Issue by rami-prilutsky** [oracle/node-oracledb#112]
Until Ref Cursors will be supported, are there any other alternatives to return record sets from procedures and retrieving them in node.js?

**Comment by dmcghan** [comment]
@rami-prilutsky I'm not sure how desperate you are, but where there's a will there's a way... You could use something like [PL/JSON](https://github.com/pljson/pljson) to execute a query and get JSON results. Then you could stringify the result and send that out via some out variables in a procedure. 

Because we don't currently have LOB support, you'd be limited to 32727 bytes with each out variable. This will not be an issue for smaller result sets, but for lager result sets, you'd have to split up the string across multiple out variables, then bring them back together in Node.js and use JSON.parse to bring it back to life.

It's not exactly trivial, but it would work...

**Comment by cjbj** [comment]
Until node-oracledb has REF CURSOR support, try converting from REF
CURSOR to PIPELINED results.  

Assuming your current proc returns a REF CURSOR like:

```
create or replace procedure myproc(p1 out sys_refcursor) as
begin
  open p1 for select last_name from employees where rownum <= 5;
end;
/
show errors
```

You could create a wrapper package:

```
create or replace package myplmap as
type outtype is record (         -- structure of the ref cursor in myproc
     last_name varchar2(25)
  );
  type outtype_set is table of outtype;
  function maprctopl return outtype_set pipelined;
end;
/
show errors

create or replace package body myplmap as
  function maprctopl return outtype_set pipelined is
  outrow    outtype_set;
  p_rc      sys_refcursor;
  batchsize pls_integer := 20;
begin
  myproc(p_rc);
  loop
-- fetch batches of 20 rows at a time
-- call the original procedure
      fetch p_rc bulk collect into outrow limit batchsize;
      for i in 1 .. outrow.count() loop
        pipe row (outrow(i));
      end loop;
      exit when outrow.count < batchsize;
    end loop;
  end maprctopl;
end myplmap;
/
show errors
```

Now your app can do a query like this to get the data from myproc():

```
select * from table(myplmap.maprctopl())
```

This was taken from a PHP example on p.202 of
http://www.oracle.com/technetwork/topics/php/underground-php-oracle-manual-098250.html

**Comment by cjbj** [comment]
To cross reference: the issue tracking REF CURSOR support is https://github.com/oracle/node-oracledb/issues/5

**Comment by cjbj** [comment]
The workaround code to map a REF CURSOR to a pipelined table is no longer needed because Node 0.7 supports REF CURSORs.  See https://github.com/oracle/node-oracledb/blob/master/doc/api.md#refcursors
