### ISSUE TITLE
i need help with my login

### ISSUE THREAD

**Issue by DarkNeku** [oracle/node-oracledb#1121]
I created a login with oracle, html and node.js but when trying to send data from my html form, I get an error "TypeError: connection.query is not a function oracle" I will leave the code so they can help me

```
var express = require('express');
var session = require('express-session');
var bodyParser = require('body-parser');
var path = require('path');
var moment = require('moment');
var oracledb = require('oracledb');
var bcrypt = require('bcrypt');
var jwt = require('jsonwebtoken');

var connection =  oracledb.getConnection({
	user: "",  
     password: "",  
     connectString: ""  
});

var app = express();
app.use(session({
	secret: 'secret',
	resave: true,
	saveUninitialized: true
}));
app.use(bodyParser.urlencoded({extended : true}));
app.use(bodyParser.json());

app.get('/', function(request, response) {
	response.sendFile(path.join(__dirname + '/login.html'));
});


app.post('/auth', function(request, response) {
	var nombre = request.body.nombre;
	var password = request.body.password;
	if (nombre && password) {
		connection.execute('SELECT * FROM camaras.usuario WHERE nombre = ? AND password = ?', 
			[nombre, password], 
			function(error, results, fields) {
			if (results.length > 0) {
				request.session.loggedin = true;
				request.session.nombre = nombre;
				response.redirect('/home');
			} else {
				response.send('Incorrect Username and/or Password!');
			}			
			response.end();
		});
	} else {
		response.send('Please enter Username and Password!');
		response.end();
	}
});

app.get('/home', function(request, response) {
	if (request.session.loggedin) {
		response.send('Welcome back, ' + request.session.nombre + '!');
	} else {
		response.send('Please login to view this page!');
	}
	response.end();
});

app.listen(3000);
```

**Comment by dmcghan** [comment]
There are a couple of issues here. The first, and largest, is that it appears you are saving passwords in cleartext. You should never, ever ever ever ever ever store your user's passwords in cleartext. Not even as a demo or proof of concept, because oftentimes that code lands in production. 

See the relevant parts of this post where I show you how to salt and hash passwords:
https://jsao.io/2015/06/authentication-with-node-js-jwts-and-oracle-database/

Each password is hashed with a unique salt to help protect against the use of rainbow tables.

Even better is to rely on a third-party identity platform, such as Oracle Identity Cloud Service. This greatly reduces the likelihood of you leaking sensitive customer information and dealing with the aftermath. I'm writing a blog post on integrating with that service now and it should be out next week.

The next issue is that you're using the wrong syntax for bind variables. See this section of the doc for the correct syntax:
https://oracle.github.io/node-oracledb/doc/api.html#bind

Finally, to your question... The code you're showing us doesn't seem to be related to the error you're getting "`connection.query is not a function oracle`". You don't have `connection.query` in the code you're showing us.

**Comment by DarkNeku** [comment]
sorry, I was doing tests and modifications, where it says 'connection.execute' should say 'connection.query', even none works for me.
my english is not very good sorry

**Comment by dmcghan** [comment]
`connection.query` isn't a method of node-oracledb. You should be using `connection.execute`.

**Comment by DarkNeku** [comment]
if that's why I change it and even then it shows me 'TypeError: connection.execute is not a function'

**Comment by dmcghan** [comment]
`connection.execute` is an asynchronous method. You're using it as a synchronous method. It's easy enough to put the `await` keyword before the method call, but you have to be in an async function to do this.

Looking at this made me realize another big issue with the code as it stands: you're not using a connection pool so this will not scale. 

My advice is to stop working on this code and work through this series:
https://jsao.io/2018/03/creating-a-rest-api-with-node-js-and-oracle-database/

Once you're done with that you should have a better idea of how to tackle your project.

**Comment by DarkNeku** [comment]
I'm doing the login to show an advance, I know that having it done will not cost me so much ...
thank you very much for the advice, I will read it

**Comment by cjbj** [comment]
I'm closing this issue since it has been superseded by #1123
