### ISSUE TITLE
SQL*Plus like connectString

### ISSUE THREAD

**Issue by sla100** [oracle/node-oracledb#1196]
SQLPlus and JDBC library accept `connectString` containing `username` and `password` with syntax:
```
username/password@connectString
```
I suggest to add this facilitation to `oracledb` methods: `getConnection` and `createPool`.

**Comment by cjbj** [comment]
Can you help us understand this desire?

Where are you getting the username, password and connection string from?

What attribute names & usage would you like?

**Comment by sla100** [comment]
Currently required invoking:
```js
const conn = await oracledb.getConnection({
	connectString: 'localhost:1521/xepdb1',
	user: 'adam',
	password: 'smith',
});
```

SQLPlus "like":
```js
const conn = await oracledb.getConnection({
	connectString: 'adam/smith@localhost:1521/xepdb1',
});
```

Generally, this allows to simplify the application configuration to one environment variable.
This extension is of course backward compatible.

**Comment by cjbj** [comment]
To continue the discussion, how critical is this?  Or is it just 'nice to have'?

Some other factors that would need to be considered:
- node-oracledb would need simple parser to decompose the string back to three parts.  (More code, more bugs - we recent had a bug restricting use of '@' in passwords in the equivalent cx_Oracle parser!)
- extra doc complexity to explain the usage
- extra testing
- how does the syntax benefit/hinder frameworks?
- is a password required if a username is given, or can 'user@localhost/orclpdb1' be used?
- what's the error behaviour if `user` and `password` attributes are also used?

**Comment by danilohgds** [comment]
@cjbj this is something which the Java driver implements as far as I can tell.
 Formats are usually as follows(ignore the thin jdbc part):

jdbc:oracle:thin:[USER/PASSWORD]@[HOST][:PORT]:SID

jdbc:oracle:thin:[USER/PASSWORD]@//[HOST][:PORT]/SERVICE

I usually try to persuade people away from this design in Java as it does imply some downsides:
- logging of the connection string parameter is not longer possible since password is built in.
- the overall take on variable management is that passwords should be encrypted, this approach either opens for plain string passwords...or fully encrypted string including hostname...which is a hassle.

**Comment by cjbj** [comment]
@danilohgds good points.
