### ISSUE TITLE
How to close database session after every connection.execute without connection.release?

### ISSUE THREAD

**Issue by gellban** [oracle/node-oracledb#1221]
I just have one **oracledb.getConnection** running when the nodes API starts. So, every RESTful request just do **connection.execute** keeping the database connection open to accelerate the API. The problem that **connection.execute** create a new session in v$session without closing it. 
In other words, the RESTful request needs running connection.execute X times (every second) which creates X database session. 

Is there any method in "Node-oracledb" module, to close just this session without closing the database connection?

**Comment by cjbj** [comment]
`connection.execute()` doesn't affect v$session:

```javascript
    connection = await oracledb.getConnection(config);

    const sql = `select count(*) as count from v$session`;
    for (let i = 0; i < 10; i++) {
      const result = await connection.execute(sql);
      console.log(result.rows[0][0]);
    }
```

Gives (for me):

```
53
53
53
53
53
53
53
53
53
53
```

Do some debugging/logging to confirm how many `getConnection()` calls you are making.

For any service where there is idle time between requests, you'll probably find it better (for high availability) to use a connection pool, even if there is only one connection in the pool.  Start the pool when Node.js starts, then use `getConnection()` and `close()` for each user request.

**Comment by gellban** [comment]
I did not have the access permissions to v$session; I just got a report. Now, I have the permissions and **yes "connection.execute() doesn't affect v$session"**.

I will check using pool instead of oracledb.getConnection without release which I reconnect when the server loose DB connection for high availability, but my approach has an issue when several users in parallel reconnect to db. Pool should be work for me better. I will check this code: https://stackoverflow.com/questions/29846188/node-js-express-oracle-connection-pooling-ora-24418-cannot-open-further-sess

Thank you very much for your advice and quick prompt!

**Comment by gellban** [comment]
Thank you so much for your help!

**If you can help me more understand the pool in Nodejs more, that will be great.**

I have follow up question about Pool. When we create the pool "oracledb.createPool" at the start of Node.js, does the pool close automatically when we stop the node (e.g., kill process, or forever stopall)? 
If the database session has been killed after 30 minutes (IDLE_TIME=30), **does the pool starts a new connections automatically?**

**Comment by cjbj** [comment]
> I have follow up question about Pool. When we create the pool "oracledb.createPool" at the start of Node.js, does the pool close automatically when we stop the node (e.g., kill process, or forever stopall)?

There are really 3 bits to a 'connection': 1. the memory structure in node-oracledb that is returned by a `getConnection()` call, 2. the network "pipe" to the database, and 3. a server process on the database computer.

A pool can be 0 or more connections.  They start with all three of the above parts, but network glitches or DB outages can mean that a `pool.getConnection()` will return the memory structure but, when you try to execute a statement, you will get an error.

In other cases, the application may close while leaving network pipe or database server process running.  The DB will eventually do some kind of "dead client detection" and clean up.  There are various parameters that can be used to make this happen sooner rather than later.

At the end of your application you should always close the pool.  Use a `drainTime` of 0 or greater.  See the end of [connectionpool.js](https://github.com/oracle/node-oracledb/blob/master/examples/connectionpool.js#L98-L111).  This will close connections and the pool cleanly.

> If the database session has been killed after 30 minutes (IDLE_TIME=30), does the pool starts a new connections automatically?

This is an example of the case mentioned above: you can end up with the node-oracledb memory structure (the connection returned from `pool.getConnection()`) that seems valid until you try to use it.

Node-oracledb (use a recent node-oracledb version and recent Oracle Client) can ping connections about to be returned by `pool.getConnection()` and reconnect if they have been killed.  This means the app doesn't realize the connection was recreated. But this ping is timing dependent so your app may sometimes get an error when it executes a statement on a connection.

The documentation explicitly recommends disabling user profile limits, and making sure firewalls don't kill connections.  You want pooled connections to be available when users request them, because creating connections can be slow. 

I'd recommend reading the documentation on [Connection Pooling](https://oracle.github.io/node-oracledb/doc/api.html#connpooling) in detail.

**Comment by gellban** [comment]
Thank you so much for answering all my questions with further explanation.
