### ISSUE TITLE
 Incorrect large number

### ISSUE THREAD

**Issue by chenliang0571** [oracle/node-oracledb#1275]
1. What versions are you using?
* Database: Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
* process.platform: 'win32'
* process.version: 'v12.14.0'
* process.arch: 'x64'
* require('oracledb').versionString: '4.2.0'
* require('oracledb').oracleClientVersionString: '19.6.0.0.0'

2. Is it an error or a hang or a crash? 
No 

3. What error(s) or behavior you are seeing?
insert a big number `4520169772808855`, database save it as `4520169772808860`.

4. Include a runnable Node.js script that shows the problem.

Table
```
CREATE TABLE"test_table" (
"table_id1" NUMBER(19),
"table_id2" NUMBER(19),
"table_idstr" VARCHAR2(19)
)
```
Nodejs
```
const oracledb = require('oracledb');
const connection = await oracledb.getConnection({
	user: "xxx",
	password: "xxx",
	connectString: "xxx"
});
console.log(await connection.execute(
	`INSERT into "test_table" VALUES(:1, :2, :3)`,[4520169772808855, String(4520169772808855), "4520169772808855"]
));
console.log(await connection.execute(
	`SELECT * FROM "test_table"`
));
```
output:
```
{ lastRowid: 'AAAIjEAQAAAABDfAAA', rowsAffected: 1 }
{
  metaData: [
    { name: 'table_id1' },
    { name: 'table_id2' },
    { name: 'table_idstr' }
  ],
  rows: [
    {
      table_id1: 4520169772808860,
      table_id2: 4520169772808855,
      table_idstr: '4520169772808855'
    }
  ]
}
```

**Comment by anthony-tuininga** [comment]
This is not a bug. It is due to the fact that floating point numbers do not guarantee precision beyond 15 decimal digits and here you are using 16 decimal digits! Since the Oracle client and database use a different floating point encoding method than Node.js does, you get some interesting results like the one you noted when you go beyond 15 decimal digits. The Oracle database does not store numbers in floating point format so the value is converted to decimal and then converted back to floating point again on fetch -- resulting in the conversion loss. You have a few choices:

- you can use strings to pass the data to/from the Oracle database (as you noted)
- you can use binary_double and binary_float column types which store floating point numbers in the database

Hope that is helpful!

**Comment by ordimans** [comment]
Can you say me if it's the same problem with trunc function ?

I have this query for example :
 ``` trunc(((i.date_creation + val_int/24)-sysdate)*24,2) ```

And in the result, some rows have very long decimal...
 ```
-900.36
-963.9300000000001
 -966.4200000000001
-987.14
```
No problem when i executed the SQL directly.


25/5000
Should I do otherwise?

**Comment by cjbj** [comment]
It's not how you get the number (e.g. with `TRUNC`), it is how the number is represented internally in Oracle and/or Node.ks. Conversion between the Oracle decimal representation and Node.js's floating point also has an impact.  Read https://oracle.github.io/node-oracledb/doc/api.html#numberhandling and https://oracle.github.io/node-oracledb/doc/api.html#fetchasstringhandling

The statement "No problem when i executed the SQL directly." has no meaning because whatever you queried with will do its own formatting for display.  For example, if you use SQL*Plus then you can affect the display with SET NUMWIDTH and SET NUMFORMAT.

This isn't a great example, but gives a picture of how the formatting in the query tool can affect what you see:
```
SQL> select 1/3 from dual;

       1/3
----------
.333333333

SQL> set numwidth 20
SQL> select 1/3 from dual;

                 1/3
--------------------
.3333333333333333333

SQL>
```
