### ISSUE TITLE
selects versus inserts

### ISSUE THREAD

**Issue by carterw** [oracle/node-oracledb#129]
I'm experimenting with this driver to try to understand how feasible it would be to port some existing Java code to Node. Maybe I'm wrong, I'm thinking this driver does not yet have anywhere near the feature set that exists in the Java JDBC, is that an accurate statement? 

For example, with Node you can currently perform selects with an ordinary string;
"select * from mytable where my_id='id123';"

However you can't do inserts in the same way, you get an error result;
"insert into mytable values (001005003, 'mystring', null, 0, 0, sysdate);"

Instead you apparently have to use a specific syntax?;
"INSERT INTO test VALUES (:id, :nm)",
              [2, 'Alison'],  // Bind values

Also I am not seeing an example that invokes stored procedures?

**Comment by nelreina** [comment]
About the insert statement I dont know, because I never did use them in node yet. 
But calling a procedure is well documented. You call a procedure by building the correct string.

```PLSQL
BEGIN store_procedure(:arg1, :arg2): END; 
```
Easy like that. I created a abstraction function that build this string for me.

**Comment by cjbj** [comment]
@carterw You can insert without binding.  However, for performance, security and scalability you probably do want to bind.  Binding is useful in node-oracledb as it is with JDBC: http://docs.oracle.com/cd/B28359_01/appdev.111/b28765/addfunc.htm#TDPJD210

You might be getting an error because you have a trailing semicolon in the SQL statement.

What features are you looking for? Database features like LOBs and Result Sets are planned. Other features will depend on user demand.  Node-oracledb doesn't aim to provide some low level APIs e.g. a prepare statement because the statement caching feature of the underlying OCI libraries mean the complexity of a two step prepare & execute sequence isn't required.
