### ISSUE TITLE
Cursor implementation and result set streaming

### ISSUE THREAD

**Issue by soyuka** [oracle/node-oracledb#13]
Hi, 

While fetching big data it can be useful to work with a cursor to avoid overheating the memory.
Also, a way to `stream` data could be very interesting! 

Thoughts? 

#3

**Comment by rinie** [comment]
Internally StmtImpl::fetch uses OCIStmtFetch2 with OCI_FETCH_NEXT and offset 0.

IMHO it would be nice if a second call to connection.execute with null as sqlStatement would fetch the next numRows of the data set. Offcourse this means that some data must be buffered until the next execute, instead of freed in Async_AfterExecute

**Comment by cjbj** [comment]
There is more discussion in https://github.com/oracle/node-oracledb/issues/24

**Comment by bjouhier** [comment]
:+1:  on this one.

BTW, I contributed the reader API in the node-oracle driver (see https://github.com/joeferner/node-oracle/blob/master/README.md#querying-large-tables). So I can help if nothing's been done on the C++ side yet.

**Comment by cjbj** [comment]
@bjouhier work is in progress. Your comments on how you would consume results would be interesting. Would an event model be useful?

**Comment by bjouhier** [comment]
@cjbj Great news.

My preference goes to a simple callback based API. If you provide something like `nextRows(count, callback)` you can easily scaffold any other type of API on top of it. For example, you can easily create an evented API by reading with `nextRows` and emitting 'row' events for every row. You can also easily implement a stream on top of it. Going the other way around (layering a simple callback on top of an evented API) is not impossible but it is more challenging.

I would only provide `nextRows` in the C++ driver and leave the event/streams scaffolding to a JS layer (which may be provided by your driver or by separate packages). For our own use cases, we would go directly to the `nextRows` API because we want maximum efficiency and we are using a simple streams library that we can layer on top of it (https://github.com/Sage/ez-streams + https://github.com/Sage/ez-oracle).

If you decide to go with an events first API, then it is very important that you provide pause/resume calls. An evented API without proper flow control would be useless for us because it is very likely that rows will come in faster than we can consume them.

**Comment by rinie** [comment]
:+1: on basic callback approach and additional layers optional in JS

**Comment by cjbj** [comment]
@bjouhier @rinie thanks for the constructive comments.

**Comment by wilkolazki** [comment]
+1 on this issue.
At least basic callback to fetch next rows would be appreciated. 

In the long term, I would like to see a readable stream to fetch data, writeable stream to insert or update many rows with the same dml statement but different binds, and maybe a duplex stream to pass bind to pl/sql block and get the objects with added OUT and modified INOUT parameters.

**Comment by cjbj** [comment]
node-oracledb 0.7.0 is available and has Result Set support. https://github.com/oracle/node-oracledb/blob/master/doc/api.md#resultsethandling

Remember to close() the result set when you have fetched all the rows, or don't want to continue fetching rows.
