### ISSUE TITLE
How to do certificate based authentication using this module?

### ISSUE THREAD

**Issue by deostroll** [oracle/node-oracledb#1312]
For e.g. having a username and a SSL certificate to authenticate with the oracle database. I couldn't find anything in the documents. Other solutions talk about a "wallet" you have to provision this on the server and client machine. How can you go about provisioning a wallet on a client machine with bare nodejs and oracle instant client installed?

**Comment by cjbj** [comment]
It would be the same as you do in SQL*Plus - it's not specific to node-oracledb.

Maybe @perpetualv can comment.

**Comment by perpetualv** [comment]
@deostroll  - PKI authentication for the database is an extension of setting up TLS network encryption. 
1) You first provision a certificate for the database server (the certificate store is called an "Oracle wallet" - it's similar in function to a JKS)
2) Your client has to have the trusted root certificate that issued the server's certificate - again, that's stored in an Oracle wallet.

Optional if you want to configure this for mutual authentication where the client also authenticates via certificate would be:
1) You provision a certificate for your client and store that in the client's wallet
2) Your database server has to have the trusted root certificate that issues the client's certificate in the server wallet
3) Your database user needs to be updated so that it uses "external" authentication using the subject in the client certificate - something like this:
alter user deostroll identified externally as 'cn=arun,dc=hacker,dc=without,dc=ahat';

For more information, take a look at [chapter 21 of the Database Security guide
](https://docs.oracle.com/en/database/oracle/oracle-database/19/dbseg/configuring-secure-sockets-layer-authentication.html#GUID-6AD89576-526F-4D6B-A539-ADF4B840819F)

**Comment by deostroll** [comment]
@perpetualv Thanks for the reply.

How do we create an oracle wallet on the client side if the client is a container? Namely the binaries for the wallet creation would be absent on the container. Do we create this externally in some external storage (like elsewhere on the host machine file system) and mount the appropriate location when we start the container?

**Comment by cjbj** [comment]
@perpetualv ping

**Comment by perpetualv** [comment]
Yes. you would have to create the wallet outside of the container if the binaries to create it aren't within the container.

**Comment by deostroll** [comment]
Can I go about creating the wallet from a containerized db server?

I have tried an external-password-store exercise to understand how to create/use oracle wallet. Here is what was done:

1. On the container created a wallet profile for a user. 
2. Then using docker cp I have copied the wallet contents from the container to a host machine.
3. From this host machine I copied the wallet folder (with contents) over to my node.js app in my local dev laptop. This was copy/pasted to the app's root folder inside a folder called `wallet`
4. Created a sqlnet.ora file inside `wallet` folder with the following contents:

```
WALLET_LOCATION=

(SOURCE=

(METHOD=FILE)

(METHOD_DATA=

(DIRECTORY=D:\code\js\my-oracledb-node-proj\wallet)

)

)
```
5. Tried the following code:

```JavaScript
const opts = {
externalAuth: true,
connectString: '<server>:<port>/<oracle_service_name>'
}

oracledb.createPool(options, (err, pool) => {
    pool.getConnection((err, cxn) => {
         // getting error here...ORA-01017
    }
});
``` 
What am I doing wrong?

**Comment by cjbj** [comment]
Whether it's a container or not shouldn't matter.  Make sure your sqlnet.ora is being loaded - is it in a default location, are you using initOracleClient(), or are you setting TNS_ADMIN? Without knowing the error it's hard to guess what is happening.

Regardless, your question isn't specific to node-oracledb so feel free to contact Oracle Support for help with wallets - you can log an SR using SQL*Plus.

**Comment by deostroll** [comment]
I was able to figure this out eventually. Originally posted the solution [here](https://stackoverflow.com/a/65802926/145682). Reproducing here for convenience. 

I adjusted the `sqlnet.ora` as follows:
```
WALLET_LOCATION=

(SOURCE=

(METHOD=FILE)

(METHOD_DATA=

(DIRECTORY=D:\code\js\myoracledb-app\wallet)

)

)

SQLNET.WALLET_OVERRIDE=TRUE
```
Next, the pool options were defined as follows:
```
const poolOptions = {  
  externalAuth: true,
  connectionString: 'ORCLCDB'
};
```
The `ORCLCDB` service name was defined in the `tnsnames.ora`.
```
ORCLCDB =
  (DESCRIPTION =
    (ADDRESS_LIST =
     (ADDRESS = (PROTOCOL = TCP)(HOST = <host_ip_or_name>)(PORT = <server_port>))
    )
    (CONNECT_DATA =
     (SERVICE_NAME =ORCLCDB)
    )    
   )
```
Both `sqlnet.ora` and `tnsnames.ora` file was placed in the wallet folder. Set `TNS_ADMIN` environment variable to the wallet folder.

This exercise although not related with certificate based authentication does help understand the general process.

**Comment by perpetualv** [comment]
@deostroll - for the tnsnames.ora file, was the protocol TCP or TCPS? TCPS should have been required to do certificate authentication.

regards, Russ
