### ISSUE TITLE
Windows 7 32 bit : NJS-045: cannot load a node-oracledb binary for Node.js 12.18.3 (win32 ia32) 

### ISSUE THREAD

**Issue by kishant777** [oracle/node-oracledb#1341]
Hello

I have an electron desktop application. I am using node oracledb module for connecting with oracle database. I bundled the exe using electron-builder, and it works fine with windows 64 bit version. But I face error with windows 7 32 bit as shown in attachment.

I use "electron-builder build --x64 --ia32 --win  --publish never" command to build my electron application. --ia32 is for 32 bit windows. In the error it looks for oracledb-5.1.0-win32-ia32.node. Checking oracledb in node modules in node modules there is no such file. Below are the attachments of error, electron-builder.yml and package json.

![image](https://user-images.githubusercontent.com/55782035/107730597-d7f99480-6d19-11eb-8af0-68ea329f3466.png)
![builder](https://user-images.githubusercontent.com/55782035/107730776-4179a300-6d1a-11eb-9591-e64f84e3d127.JPG)
![package](https://user-images.githubusercontent.com/55782035/107730779-42aad000-6d1a-11eb-838e-2bea0e48c880.JPG)

**Comment by cjbj** [comment]
For Windows, we only provide a x86 64-bit binary.  If you are running any other Windows you will need to compile a binary yourself, and will find it convenient to [self-host](https://oracle.github.io/node-oracledb/INSTALL.html#selfhost).  Good luck! We are not planning on providing anything more than we currently do.

PS General note to everyone: please don't use screenshots because (i) not everyone can read them (ii) they are pretty much impossible to cut & paste from to quote, or to replicate a problem.
