### ISSUE TITLE
macOS Big Sur with node-oracledb 4.2: DPI-1047 Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 1)

### ISSUE THREAD

**Issue by christianbirg** [oracle/node-oracledb#1350]
1. What versions are you using?

process.platform = darwin
process.version v14.5.0
process.arch = x64
require('oracledb').versionString = 4.2.0
require('oracledb').oracleClientVersionString Uncaught: Error: DPI-1047: 
Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 1): image not found". See https://oracle.github.io/odpi/doc/installation.html#macos for help

2. Is it an error or a hang or a crash?
error

3. What error(s) or behavior you are seeing?

In version 4.2. the oracledb package can not recognize the library libclntsh.dylib. I am working on Macbook 2019 (2.4 GHz 8-core Intel Core i9, 64 GB 2667 MHz DDR4) with Big Sur installed. Accordingly, I can only install Instant Client 19.8. On version > 5, this is not a problem. However, I can't do a major version bump in this project, as this could destroy about 200 other developers and the functionality of already existing source code

My attempts so far:
1. downloaded version 19.8, mounted it, executed install script and then
- symlinked folder (and put ~/lib and /usr/local/lib to path)
- copied folder into /usr/local/lib (as subfolder and directly into the /usr/local/lib)
- folder copied to ~/lib (as subfolder and directly in the /usr/local/lib)
2. installation over brew

Nothing worked. I have looked at all the issues that encountered the exact same error message.

Could it be that the precompiled headers in node_modules/oracledb/build/Release only work up to certain Mac versions?

How can I copy these headers manually? 

Thank you for your help :-)

**Comment by cjbj** [comment]
As a workaround you might find that setting DYLD_LIBRARY_PATH helps, though beware that this variable doesn't propagate down to subshells.

If you want to play with compile & link options, then you can update [binding.gyp](https://github.com/oracle/node-oracledb/blob/master/binding.gyp), and follow [Node-oracledb Installation from Source Code](https://oracle.github.io/node-oracledb/INSTALL.html#github).  Compare https://github.com/oracle/node-oracledb/blob/v5.1.0/binding.gyp#L76 vs https://github.com/oracle/node-oracledb/blob/v4.2.0/binding.gyp#L78  The change was made to help compensate for Apple's continual evolution on how linking behaves.

If all else fails, then you really will have to 'keep up with the times' and upgrade node-oracledb. Then you can use any of the ways to locate Instant Client mentioned in https://oracle.github.io/node-oracledb/INSTALL.html#instosx Or you can downgrade your OS!

**Comment by christianbirg** [comment]
Okay this post is giving the solution. 

https://github.com/oracle/node-oracledb/issues/1239#issuecomment-624993384

Is there a possibility to  patch version 4.2?

**Comment by anthony-tuininga** [comment]
Patch 4.2 yourself? As you've already acknowledged, 5.1 doesn't have this issue and the only reason you don't want to upgrade is because you don't want to test at this point in your project. I'll let @cjbj comment later when he is awake, but I suspect he will agree with me that we aren't likely to provide a 4.2.1 release at this stage.

**Comment by cjbj** [comment]
Did DYLD_LIBRARY_PATH work for you?

[Issue #1239](https://github.com/oracle/node-oracledb/issues/1239#issuecomment-624993384) is the same solution I gave you before - you need to change binding.gyp.  For the production release we didn't add support for $HOME, since I couldn't find a way to make this relative to the installer's $HOME (and not the value of $HOME during build time).  The link option wasn't needed with older macOS releases, since they automatically used the path.

Sorry, we're not planning on doing a 4.2.1 release; we're trying to keep momentum moving forward.  It's super simple to build on macOS. Install Xcode and the command line tools, and then run 'npm install' over a source tree.  If you want to share between developers, you can host your own packages.  The install doc covers all this.  Good luck!

**Comment by cjbj** [comment]
@christianbirg I'm still curious if `DYLD_LIBRARY_PATH` helped.
