### ISSUE TITLE
 Error: NJS-021: invalid type for conversion specified for "OracleDB.fetchAsString = [ OracleDB.CLOB, OracleDB.NCLOB ]"

### ISSUE THREAD

**Issue by djavi** [oracle/node-oracledb#1351]
When executing select queries, LOBs are returned as [Object object] so trying to convert them to string/buffers but they return this error.

**Comment by cjbj** [comment]
Please answer the issue logging template https://raw.githubusercontent.com/oracle/node-oracledb/master/.github/ISSUE_TEMPLATE/general-questions-and-runtime-problems.md

And provide a runnable script including SQL that creates the table.  Thanks!

**Comment by djavi** [comment]
I am not able to run my code because 
"oracledb.fetchAsString = [ oracledb.CLOB, oracledb.NCLOB ];
oracledb.fetchAsBuffer = [ oracledb.BLOB ]"

returns "Error: NJS-021: invalid type for conversion specified".

I don't think this has anything to do with the SQL scripts :(

**Comment by cjbj** [comment]
Per the [doc](https://oracle.github.io/node-oracledb/doc/api.html#propdbfetchasstring), just use oracledb.CLOB since this also applies NCLOB columns.

We will look at reducing the confusion so it 'just works' and so you (and other people!) don't have to read the documentation.  And/or fix the documentation about allowed values in the array.

**Comment by djavi** [comment]
Oh I see!!! 

Thank you, works as expected now 👍
