### ISSUE TITLE
Docker image with Instant Client 19 with node 14^

### ISSUE THREAD

**Issue by danielsrod** [oracle/node-oracledb#1378]
So, I ust wanna know, if there exists a Docker Image with the title requirements.

Instant Client 19
NodeJS 14^

Thanks anyway.

**Comment by cjbj** [comment]
Looks like we haven't built one yet: https://github.com/oracle/docker-images/issues/1940

It's pretty easier to build your own.  Look at https://blogs.oracle.com/opal/docker-for-oracle-database-applications-in-nodejs-and-python-part-1

Also see https://github.com/oracle/docker-images/blob/main/OracleLinuxDevelopers/oraclelinux7/nodejs/14/Dockerfile and https://github.com/oracle/docker-images/blob/main/OracleLinuxDevelopers/oraclelinux7/nodejs/12-oracledb/Dockerfile If you want to use the node-oracledb RPM (instead of installing via your package.json) you'll find it in the channel https://yum.oracle.com/repo/OracleLinux/OL7/developer/nodejs14/x86_64/

**Comment by danielsrod** [comment]
Ok then.

Thanks for the reply.

**Comment by cjbj** [comment]
@danielsrod there's now a Node.js 14 image with node-oracledb.  It uses Instant Client 21: this will connect to DB 12.1 or later.

https://github.com/orgs/oracle/packages/container/oraclelinux7-nodejs/2689573?tag=14-oracledb

You can get it with:

`docker pull ghcr.io/oracle/oraclelinux7-nodejs:14-oracledb`

**Comment by danielsrod** [comment]
Thanks a lot.

It will be useful.
