### ISSUE TITLE
Pool health

### ISSUE THREAD

**Issue by ronnn** [oracle/node-oracledb#1379]
Hey,

I have a general question regarding pool health. 

We're running node-oracledb with a static pool connected to Exadata. Unfortunately, there's a bug in Oracle that is currently not easily fixable for us, therefore we were tasked with implementing a workaround. The bug triggers the ORA-00600 error. Whenever the error occurs the connection may remain in an unusable state.

The current workaround is to drop the connection completely. It works fine to make sure that the error does not interfere with any other requests. But we noticed that the pool is not used in the way we would expect it to. We set `poolMin=poolMax` and `poolIncrement=0` as per the documentation (_“The values of poolMin and poolMax should be the same (and poolIncrement equal to zero). This avoids connection storms which can decrease throughput.”_ http://oracle.github.io/node-oracledb/doc/api.html#-1531-connection-pool-sizing). However, this leads to the pool becoming unhealthy. The connection is dropped in case of error and the pool is not refilled to have the maximum number of connections. Setting `poolIncrement=poolMax` does mitigate this in some way but may lead to poor performance as the connections are only re-established, when connections are requested. So we’re wondering if there’s a better solution.

Is there a way to implement some background process to refill the pool? 

Another alternative could be to use Connection Pool Pinging (http://oracle.github.io/node-oracledb/doc/api.html#-1536-connection-pool-pinging, `poolPingInterval=0`). With this we would not drop the connection on error but use pinging to make sure that requested connections are in a usable state. Would this mechanism detect that there has been such an error on connections? Until now we didn't have a chance to test if the pinging overhead is low enough to justify this. Maybe somebody has some practical knowledge with this.

Thanks,
Ronald

**Comment by cjbj** [comment]
Are you actually experiencing poor performance on user requests where a connection has to be re-established?  How often are you having to drop connections from the pool? Can you let me know more about the ORA-600?  What arguments?  Is there an SR or Oracle bug? (You can [email me](https://github.com/cjbj) if you like).

The underlying pool behaviors vary with Oracle Client version.  There were some nice changes with 21c client for poolMin.  One was regarding re-establishment: now during the first get-connection call after an outage that causes all connections to be unusable, the pool creates up to poolMin sessions instead of just the increment number of sessions. This was the enhancement logged & resolved for https://github.com/oracle/node-oracledb/issues/1235. Another enhancement in 21c was with how the [pool shrinks](https://docs.oracle.com/en/database/oracle/oracle-database/21/nfcon/oracle-call-interface-session-pool-improvements-282887841.html) down to poolMin.

I would hope a round-trip ping (from poolPingInterval or ping()) would detect a problem with a connection for any ORA-600 that invalidates the connection, but that might depend on the details.  A pingInterval ping would drop the connection if it was deemed unusable. I'd prefer not to see poolPingInterval set to 0 because the round-trip cost can mount up in time and DB CPU, depending on network speed.

What I would suggest is use Instant Client 21 and try node-oracledb 5.2.0-dev, since there were [dead connection detection](https://github.com/oracle/node-oracledb/commit/9c7aa31dfe740b0ec1556c707d15f9d6def3b0e6) improvements to when connections are checked for dead connections and dropped from the pool.  If you have to use an older Oracle Client, I wonder whether having a non-zero increment would help?  Recent-ish versions let you set a non-zero increment even if poolMin & poolMax are the same; I don't know what value is used for growth to get back to poolMin.  @krismohan would know.

**Comment by sudarshan12s** [comment]
@ronnn,
I assume you are using homogeneous pool. In 19c, following is the behaviour 

The connections are added to satisfy poolMin value, i.e it uses poolMin-openconn or poolIncrement configured to expand the pool, which ever value is higher.
 
Openconn is busy+freeconns in pool.

**Comment by ronnn** [comment]
@cjbj Thank you for the quick reply!

We were in contact with our DBAs and Oracle and they said the trace matches Oracle bug 29720373. For this a patch was applied, but it didn't fix the problem. The ORA-00600 error is triggered when the application server issues a long running database operation for which the request times out or is cancelled by the client. In that case we break and release the connection to free up the resources. If we release the connection without dropping, another request might receive the error when reusing that connection. I tried Instant Client 21 and node-oracledb 5.2.0-dev but the issue remains.

Our problem with the current approach of dropping connections is, that the connections are not re-established. With `poolIncrement=0` the static pool is drained until only one connection remains and then it never is re-filled to `poolMax`. When setting `poolIncrement>0` the connections are re-established, but not until `poolMax` but to a maximum of `poolMax-x`. I guess this is because every time the pool is used, there's at least one connection already in use as @sudarshan12s mentioned?! Or is this possibly a bug?

The database version is Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production Version 19.7.0.0.0.

Versions when developing locally:

```
$ node
Welcome to Node.js v14.16.0.
Type ".help" for more information.
> process.platform
'win32'
> process.version
'v14.16.0'
> process.arch
'x64'
> require('oracledb').versionString
'5.1.0'
> require('oracledb').oracleClientVersionString
'19.8.0.0.0'
```

Versions deployed:

```
# node
Welcome to Node.js v14.17.0.
Type ".help" for more information.
> process.platform
'linux'
> process.version
'v14.17.0'
> process.arch
'x64'
> require('oracledb').versionString
'5.1.0'
> require('oracledb').oracleClientVersionString
'19.8.0.0.0'
```

I created a simple project to reproduce our findings: https://github.com/ronnn/pool-refill. After the process is started it takes some time until the queue fills up and then after some more time the getConnection calls time out with  `Error: NJS-040: connection request timeout. Request exceeded queueTimeout of 60000`. The example is simplified because all connections are dropped after usage, however we think this shows what we're struggling with. Is there anything that can be done to make sure that the connections are re-established after dropping?

**Comment by cjbj** [comment]
@ronnn there's some ongoing discussion about the Session Pool on this. We'll update you. 

Do you need to kill every connection - I assume not, but how frequent is this?  Are you actually experiencing performance degradation when the pool has to re-establish itself?

**Comment by sudarshan12s** [comment]
@ronn,

Yes in 19c , poolIncr has to be >= poolMin so that the expansion of pool
can happen for atleast poolMin value.   For 21c, poolIncr can be 0.

pool expansion shall happen in get-connection when the freeconns count is 0
and open connections are less than poolMax.



you can try spawning 2 get-connection calls when pool is drained to size 1.
then since freeconns=1 , the second get-connection request starts pool
expansion till poolMin.


I modified your test case to add  a function like below after the pool is
drained , i see stats showing the expanded pool size. I am saying in your
case, when there is a contention like

above it causes expansion .    can you confirm.


  for (conIndex = 0; conIndex < 2; conIndex++) {
          console.time();
        let conn =   pool.getConnection();
          console.timeEnd();
        conns.push(conn);
      }
      for (conIndex = 0; conIndex < 2; conIndex++) {
        let conn = conns[conIndex];
         conn.close({ drop: true });
      }





Regards,

**Comment by ronn** [comment]
@ronnn

**Comment by cjbj** [comment]
@ronnn Here's [another script](https://gist.github.com/cjbj/3b75c8ea4fe9f30d3611e2672f9bf6b0) that drops all connections.

You can see with `poolIncrement = poolMin = poolMax`, that after the pool is emptied, the next `getConnection()` call will re-establish all the connections, but will take the same amount of time as initial pool creation.  With Oracle Client 19.8:

```
$ node issue1379a.js
Pool created: 3.991s
poolMin: 10 poolMax: 10 poolIncrement: 10 connectionsInUse: 0 connectionsOpen: 10
Dropping initial connections
poolMin: 10 poolMax: 10 poolIncrement: 10 connectionsInUse: 0 connectionsOpen: 0
first getConnection: 3.623s
poolMin: 10 poolMax: 10 poolIncrement: 10 connectionsInUse: 1 connectionsOpen: 10
second getConnection: 0.245ms
```

(When `poolMin = poolMax`, you can only set `poolIncrement` > 0 when using Oracle Client 18.x or later)

If only a few of the connections are dropped, then the next `getConnection()` won't magically re-build the connection pool because the session pool design is to return an available connection immediately.  The pool heuristics are biased that way.  And I know the Session Pool team want to keep the logic fast.  As @sudarshan12s pointed out, the growth happens when there is contention and the pool really needs to grow.

I'm still curious how frequently you are having to drop connections from the pool, and whether you are seeing any performance issues with the pool re-establishing itself.  You said the pool was drained until you only had one connection.  Let us know the progress to getting a DB patch.


Action items for us:
- @sudarshan12s pointed out to me that the Oracle Client 21c `poolMin` improvement probably doesn't help node-oracledb because node-oracledb calls the underlaying session pool with a WAIT mode.  I want to dig into this more with the OCI team.
- Improve our pool sizing doc discussion (More doc!  Yay!)  
- Review why your particular ORA-600 wasn't being detected as making the connection unusable
- Review whether we think it's worth internally dropping connections that experience any ORA-600 (under the assumption that ORA-600's are rare).

**Comment by ronnn** [comment]
@cjbj Thanks for the other example. 

Currently dropping the connections happens every time a potential ORA-00600 could be triggered which in our case is every time a request to the application server is aborted or times out. Specifically requests with long running operations that update a lot of data through triggers. The DB patch is planned to be installed in July.

The time to re-build the pool isn't that critical to us. One request will be slower but the followings will be fast again. However, because the pool only re-builds after it was emptied, there's a timeframe in which the application needs to deal with e.g. only 2 usable connections. This won't change as long as no further connections are dropped. I don't have a working example yet, but it looks like that is a potential problem in conjunction with the Connection Pool Queue. What I see is that the queue fills up and connection requests time out. The pool "heals" (reconnects) but the following `getConnection()` calls time out anyway. I'll let you know as soon as I have a working script for this.

**Comment by cjbj** [comment]
@ronnn install the just released node-oracledb 5.2.0 production release for further testing.   This has https://github.com/oracle/node-oracledb/commit/b7abd6712814394f01cc0f52c2ddef112bc79e3a which fixed a queuing issue that may have affected the 5.2.0-dev code you tried. The buglet it fixed was not present in 5.1.

What's the `maxPool` size for you pool (presumably `maxMin` is the same)?  How long does `createPool()` take in your environment?

Do definitely know you need to force the connections closed with `drop:true`?  Are you sure that the pool doesn't automatically detect them as unusable and drop them itself, so these unusable connections are never given back to a subsequent `pool.getConnection()` call?

How often (relatively) is "every time"?

**Comment by ronnn** [comment]
@cjbj Thank you. We're now on 5.2 and the behavior persists but we found a suitable workaround (see below).

> What's the maxPool size for you pool (presumably maxMin is the same)? How long does createPool() take in your environment?

We're on `maxPool=10` and create pool takes about 1 second. 

> Do definitely know you need to force the connections closed with drop:true? Are you sure that the pool doesn't automatically detect them as unusable and drop them itself, so these unusable connections are never given back to a subsequent pool.getConnection() call?

Yes, we need to drop. The pool does not detect the error. If we ditch the dropping the next i.e. package call that updates data that triggered the ORA-00600 error will receive the error.

> How often (relatively) is "every time"?

The main issue is that there's no way for us to safely detect the ORA-00600 error on a connection after the error occurs. This is because the error is triggered only if data that should be updated by triggers on a cancelled/timed out request is updated by a subsequent package call on the same connection. As long as the faulty connection is only used for `SELECT` statements there's no error.

Therefore we came up with a workaround that isn't perfect but works in our case. Each server instance now has a pool switching mechanism. High level process:

* Create the pool and monitor for `pool.connectionsOpen < poolMin` on the active pool
* If there are less connections create a new pool and make this pool the active one after creation is finished
* Close the old pool with a drain time that is depending on the request timeout to ensure that running requests have a chance to finish

**Comment by anthony-tuininga** [comment]
>> Do definitely know you need to force the connections closed with drop:true? Are you sure that the pool doesn't automatically detect them as unusable and drop them itself, so these unusable connections are never given back to a subsequent pool.getConnection() call?

> Yes, we need to drop. The pool does not detect the error. If we ditch the dropping the next i.e. package call that updates data that triggered the ORA-00600 error will receive the error.

I'm still a bit confused about the order of events. Is this correct?

1. Acquire a connection from the pool and run a statement that takes too long.
2. In a separate thread of execution, break the connection (cancel the statement). What error do you receive in this case? Do you return the connection to the pool at this point or do you drop the connection from the pool?
3. Assuming you don't drop the connection, acquire this connection from the pool and attempt to perform an update. What error do you get this time? If you attempt to use the connection to do something else, what error do you get?

Hopefully that will clarify things for me!

**Comment by SDepn** [comment]
Hi,

I am working with @ronnn on this project. Let me try to clarify what our issue was. I'll water the issue down but this is what happened, just on a larger scale (more tables and records affected, more triggers being executed, etc.)

1. We run a statement in `connection A` that updates `record X` in `table A` via a trigger
2. While the trigger executes, we break the connection from another thread
3. The `connection A` callback either receives no error or an ORA-01013 error
4. We return `connection A` to the pool (At this point the connection is already broken but we don't know about it)
5. We run another statement and `connection A` is being reused. Depending on the type of statement the behavior differs now
    a.  We execute a SELECT statement or change records that are not `record X` in `table A`. Here everything works normally
    b. We attempt to update `record X` in `table A`. Here we get the "ORA-600 error during trigger execution..." error

As we are not able to safely know whether a connection is "broken" or not, we now always drop the connection after a break and use the workaround described above to make sure we always have a full pool. I hope this explains a bit better what happened.

**Comment by anthony-tuininga** [comment]
Thanks. That helps. After you get the ORA-600, what happens if you continue to use that connection? What errors do you get then?

**Comment by cjbj** [comment]
@ronnn @SDepn did you ever identify the root cause?  [Earlier](https://github.com/oracle/node-oracledb/issues/1379#issuecomment-849499774) it seemed the patch for Oracle bug 29720373 had not helped.

**Comment by ronnn** [comment]
@anthony-tuininga The connection stays in the faulty state and is not usable anymore. 

@cjbj Not really. The DBAs and Oracle Support are suggesting to wait until the next full patch that is planned to be installed on 12-Jun on our Exadata platform. We plan to check if the patching had any impact on the following day.

**Comment by ronnn** [comment]
@anthony-tuininga Yes, the same error - over and over.

**Comment by anthony-tuininga** [comment]
Thanks @ronn.

**Comment by ronn** [comment]
> Thanks @ronn.

Add the 3rd "n" please
Is @ronnn
