### ISSUE TITLE
ORA-12545 error

### ISSUE THREAD

**Issue by Halley73** [oracle/node-oracledb#143]
When i connect trough SqlPlus all is ok, but if i try to connect via oracledb driver i receive error:

ORA-12545: Connect failed because target host or object does not exist

**Comment by cjbj** [comment]
Not information was provided.

What's your connect string?

**Comment by Halley73** [comment]
Hi,
i have Mac Os Yosemite 10.10.4 with InstantClient 11.2 and Oracle 12.1.

This is my connection string

oracledb.getConnection(
    {
        user : "omnilab206",
        password : "omnilab206",
        connectionString : "locale"
    },

and attached the tnsnames.ora.


2015-07-21 0:28 GMT+02:00 Christopher Jones <notifications@github.com>:

**Comment by cjbj** [comment]
The correct attribute is `connectString` not `connectionString`.
This is the second report of confusion with that attribute name :(

**Comment by Halley73** [comment]
Ok, thank you very much.



2015-07-21 9:21 GMT+02:00 Christopher Jones <notifications@github.com>:

**Comment by Halley73** [comment]
Hi,
i've a question.

Can i create a connection in a js file and export?

With sqlite i have a db.js file like this:

var sqlite3 = require('sqlite3').verbose();

exports.db = new sqlite3.Database(*filename*);

2015-07-21 9:28 GMT+02:00 Luca Colombano <luca.colombano@gmail.com>:

**Comment by dmcghan** [comment]
@Halley73 Rather than create a connection and export that, I recommend you create a module that wraps a pool. There's an example of that here: https://jsao.io/2015/07/relational-to-json-with-node-js/. The example shows the module but it doesn't show where the createPool method was invoked - that was done in a different file I was using for testing. In most cases that would be one of the first things that's done when starting a Node.js process. 

I also talk about wrapper modules in this post here: https://jsao.io/2015/03/making-a-wrapper-module-for-the-node-js-driver-for-oracle-database/
