### ISSUE TITLE
Use TLS instead of MTLS

### ISSUE THREAD

**Issue by Joelith** [oracle/node-oracledb#1434]
Is it possible to use this package to connect to an Oracle Database (eg: ATP) without using a wallet? As per this documentation from Oracle:
https://blogs.oracle.com/developers/post/securely-connecting-to-autonomous-db-without-a-wallet-using-tls

That uses JDBC Thin driver, but can't work out a way to do that with this package?

**Comment by cjbj** [comment]
Not currently.  The limitation is in the Oracle Client libraries.  When this changes, we'll be shouting about it.

**Comment by Joelith** [comment]
@pavansandeep2910 @cjbj Agreed! Would love to know if the shouting should have commenced?

**Comment by cjbj** [comment]
It's been possible since what seems a long time ago: We shouted in https://blogs.oracle.com/opal/post/easy-way-to-connect-python-applications-to-oracle-autonomous-databases  Also see the doc https://node-oracledb.readthedocs.io/en/latest/user_guide/connection_handling.html#tls-connections-to-oracle-cloud-autonomous-database

**Comment by cjbj** [comment]
I should note that we are now blogging at https://cjones-oracle.medium.com and https://medium.com/@sharad-chandran so follow those blogs instead of https://blogs.oracle.com to keep up to date with news.  You can also find me at @cjbj@phpc.social :)
