### ISSUE TITLE
Dependency details of current releases.

### ISSUE THREAD

**Issue by amitagarwal-dev** [oracle/node-oracledb#1459]
Just a quick question!  
  
Is there any way to check the dependencies of a oracledb releases?
For Example, I want to know about the minimum version of oracle database, instant client and nodejs supported for oracledb-5.2.0.  
  
@cjbj

**Comment by cjbj** [comment]
@amitagarwal-dev One of the many, many todo items is to create a matrix of what we tested.  PRs welcome.

We have been testing with 11.2 client & DB since the beginning. And will do so for a while.  The Node.js version is harder to track without checking the install doc for each node-oracledb release, e.g https://github.com/oracle/node-oracledb/blob/v5.2.0/INSTALL.md

**Comment by amitagarwal-dev** [comment]
@cjbj thanks for the information.
