### ISSUE TITLE
how do I use 'Database Link' ?

### ISSUE THREAD

**Issue by sukjin** [oracle/node-oracledb#150]
I use Database Link with db tools.

for example.

SELECT a.user_id, b.user_nm
     FROM mydb a, mydb@LINK_MS b
 WHERE a.cd = b.cd

and I use node-oracledb 

so I can query single db like   SELECT * FROM mydb

but I don't know how do I use 'Database Link' like @Link_MS ...

**Comment by cjbj** [comment]
Using a DB link in node-oracledb is no different from using a DB link in tools like SQL*Plus.

**Comment by sukjin** [comment]
Is any Example with node.js? I don't know how to query db link without tnsnames.ora

**Comment by cjbj** [comment]
There isn't a specific example because there is nothing specific to node-oracledb.
If it's easiest for you to use a tnsnames.ora file, then go ahead and use one.
Otherwise you can create the db link using the normal Easy Connect `hostname:port/servicename` syntax.

(Yes, we may eventually add an example, time permitting: I recognize that if you need to ask, then we need to make it easier for you to find an answer)
