### ISSUE TITLE
Decorator for display errors

### ISSUE THREAD

**Issue by Abdel-Monaam-Aouini** [oracle/node-oracledb#1513]
https://docs.oracle.com/en/database/oracle/oracle-database/18/drdas/error-code.html#GUID-3DB3995E-5FF8-4650-9216-A5B5C41CE2D7
![image](https://user-images.githubusercontent.com/52112750/187653244-0e574420-0b7a-4325-a650-bd98c9e93e52.png)

**Comment by cjbj** [comment]
Can you explain more about how you would this to be exposed? Would like to submit a PR with the suggestion?

**Comment by Monaam12** [comment]
> Can you explain more about how you would this to be exposed? Would like to submit a PR with the suggestion?

when you have an error in your query, you don't know what's wrong, you waste a lot of time to know what's the error, these errors do not make sense,

**Comment by cjbj** [comment]
@Monaam12 what exactly are you suggesting?  The ORA errors are documented in https://docs.oracle.com/en/database/oracle/oracle-database/21/errmg/index.html  However the ORA codes are not in the scope of this project since they are returned from the DB or Client libraries to node-oracledb and we can't change or control them directly.  What do you want from node-oracledb?  A mapping to SQLCODES? More doc? Or something else? I'm interested to know.  Even if I can't make direct changes to other Oracle components I can always send feedback to the owners.

**Comment by cjbj** [comment]
@Monaam12 can you clarify what you would like?

**Comment by Monaam12** [comment]
> @Monaam12 can you clarify what you would like?

my point is about errors are not friendly for developers when you make something wrong!
I mean like this https://github.com/sequelize/sequelize/blob/main/src/errors/base-error.ts
