### ISSUE TITLE
for all GET requests, getting `ORA-03120: two-task conversion routine: integer overflow`

### ISSUE THREAD

**Issue by sidharth74659** [oracle/node-oracledb#1527]
1. What versions are you using?
```
Run at: Tue Oct 18 2022 21:42:12 GMT+0530 (India Standard Time)
Node.js version: v16.18.0 (win32 x64)
Node-oracledb version: 5.5.0
Oracle Client library version: 21.6.0.0.0
Oracle Database version: 12.1.0.2.0
```

2. Describe the problem
I debugged and noticed after executing the node file that all GET request routes are sending the `ORA-03120: two-task conversion routine: integer overflow` error while running `conn.execute(query, params)` and no POST request routes are throwing any error. And it just happens on my machine; the other teammates do not receive this issue. I tried cloning, changing ports, upgrading and downgrading oracle-instantclient, but nothing seems to work.

4. Include a runnable Node.js script that shows the problem.

```js
return new Promise(async (resolve, reject) => {
    let conn;
    try {
      conn = await oracledb.getConnection(process.env["poolAliasName"]); // connecting successful
      let result = await conn.execute(query, params); // for every GET request, throwing as error mentioned above
      resolve(result);
    } catch (err) {
      reject(err);
    } 
  });
```

can anyone if ever faced this issue or knows what's causing this.. can you kindly help me out as it's been one week and couldn't fix it

**Comment by cjbj** [comment]
What other info can you share?  Are you binding the right values to the right variables?  Are you using DB links?  What's your (and your teammates) machines - are they the same?

**Comment by sidharth74659** [comment]
> What other info can you share? Are you binding the right values to the right variables? Are you using DB links? What's your (and your teammates) machines - are they the same?

Yes they have the same machines, I'm correctly binding the right values, in fact to give you much info, when they literally run the same code and check the APIs they are getting responses, but for me, I'm getting the errors as mentioned, even worse, sometimes, the APIs I write when tested in my local machine, doesn't work once it's deployed

**Comment by cjbj** [comment]
Since you're the only one who can reproduce it, sadly you'll have to do some debugging.  Try different client libraries/databases.  Triple-check the environments are the same as your colleagues.  Check for potential hardware issues.   And what's this about deployment failures - so are you seeing the problem in two different environments.  If you can find a (small) reproducible test case, and can share the SQL to create the schema the data, then we might be able to help more.

**Comment by Corpsomium** [comment]
Went from instantclient_12_2 to instantclient_21_7 and facing the same issue.
I rolled back to instantclient_19_17 and it's working again, so something is happening with the latest instant client.

**Comment by cjbj** [comment]
@Corpsomium sorry to hear that.  See my previous comments - we need a testcase to do any followup.

**Comment by Corpsomium** [comment]
While trying to replicate the issue in another project to submit the testcase, I realised it was working with my duplicated package, but not my original one.

Tried recompiling both the specs and body of it using SQL Developer (instead of VSCode as I usually do) and it worked again, so no clue about what caused the error, but now it's gone. 🤷
