### ISSUE TITLE
Version 6.7.0 causes an error in Bun.

### ISSUE THREAD

**Issue by buwon** [oracle/node-oracledb#1707]
https://github.com/oracle/node-oracledb/blob/ed14819fb00dee235fd7d81cd0230b598fd09679/lib/util.js#L175
SyntaxError: Unexpected token ','

```javascript
traceContext.error = Object.assign({}, err); // ok
```

The above syntax causes an error in Bun.

I use Nodejs and Bun, but I get an error in Bun.

Currently, it still doesn't work on Bun 1.1.34, but I'm waiting for the day when it will work.

**Comment by sharadraju** [comment]
Is this error not there in the previous release?

**Comment by sudarshan12s** [comment]
Thanks @buwon for sharing the details. We will fix it.

**Comment by sudarshan12s** [comment]
@buwon , Can you use this patch on top of 6.7.0 and confirm if this works.
```diff
diff --git a/lib/util.js b/lib/util.js
index 82f707661..8968c86c4 100644
--- a/lib/util.js
+++ b/lib/util.js
@@ -171,9 +171,7 @@ function traceExitFn(traceContext, result, err) {
   }
 
   // Fill the traceContext.
-  if (err) {
-    traceContext.error = Object.assign(({}, err));
-  }
+  traceContext.error = err;
   traceContext.additionalConfig.result = result;
   if (this._impl) {
     // fill function call state.

**Comment by drollinger** [comment]
I have the exact same issue and can confirm that running the patch does fix things for bun. For now I'm using 6.6.0 which also works. I'm not sure why this is needed for Open Telemetry since wouldn't `({}, err)` just evaluate to err meaning the patch does the exact same thing? If it is suppose to be a shallow copy then then it should be `Object.assign({}, err)`. I don't know much about working with Open Telemetry though.

**Comment by sharadraju** [comment]
@drollinger Thanks for using node-oracledb. The extra parenthesis was added to copy all the properties including non-enumerable ones as well. Since, this is causing an issue in Bun, we re-evaluated this statement and came up with the patch. @sudarshan12s  can provide more details on this, if required.

All said and done, this will be fixed in 6.7.1.

**Comment by sudarshan12s** [comment]
> I have the exact same issue and can confirm that running the patch does fix things for bun. For now I'm using 6.6.0 which also works. I'm not sure why this is needed for Open Telemetry since wouldn't `({}, err)` just evaluate to err meaning the patch does the exact same thing? If it is suppose to be a shallow copy then then it should be `Object.assign({}, err)`. I don't know much about working with Open Telemetry though.

Yes the non-enumerable property `message` was not copied with `Object.assign({}, err)`.  But here a simple reference or assignment works as it is not used after function returns. The patch works with OT usage too.

**Comment by buwon** [comment]
It works well. Thank you.

**Comment by drollinger** [comment]
Since this issue had to do with Bun, I thought I'd drop a note in here just in case anyone is attempting to use this package with Bun. We've had issues with connections hanging after awhile even after reverting to 6.6.0. We then reverted to using node and everything worked perfectly again, so I'd highly suggest sticking with node.
