### ISSUE TITLE
Getting Error NJS-024: memory allocation failed on oracledb 1.0.0

### ISSUE THREAD

**Issue by nelreina** [oracle/node-oracledb#174]
Query works fine on 0.6.0 and 0.7.0; 
But when I ran the same query on 1.0.0 I received the mentioned error.

**Comment by cjbj** [comment]
@nelreina "we need a testcase" would normally be my first response. But what would be useful to know in this case is what the DB character set is, and what the client character set is? We haven't yet done a memory optimization that will help for some character sets.

The NJS-024 is not unexpected.  See https://github.com/oracle/node-oracledb/blob/master/CHANGELOG.md where it mentions extra memory is allocated, and where it mentions we fixed a crash allocating large amounts of memory - hence you can get the NJS-024 instead of corruption.  (I also mentioned this in https://github.com/oracle/node-oracledb/issues/65#issuecomment-131717843)

**Comment by cjbj** [comment]
PS.  Use ResultSets.

**Comment by nelreina** [comment]
@cjbj  Ok Thanks for the response. I'll dive into it on monday :-)  Have nice weekend.

**Comment by cjbj** [comment]
@nelreina Try with 1.1.  We optimized memory allocation a bit for queries in all environments.  And if the DB is using AL32UTF8 then node-oracledb 1.1 will use the same memory as 0.7, give or take allocations for other changes.

**Comment by nelreina** [comment]
@cjbj Thanks for the update. Did not had a chance to to update my system yet. Went back to V 0.7.
I will keep you updated when I do.

**Comment by rajeshpkumar** [comment]
**@cjbj ** Still i'm facing the same issue "NJS-024: Memory allocation failed". I'm using node-oracledb 1.7.1 version. Let me know if any update on this issue.

**Comment by cjbj** [comment]
@rajeshpkumar Start by RTM in case you need to tune something.  https://github.com/oracle/node-oracledb/blob/master/doc/api.md  After that, post specific questions with useful details.  Use a new thread.
