### ISSUE TITLE
Configurable DATE result type mapping

### ISSUE THREAD

**Issue by hvrauhal** [oracle/node-oracledb#20]
[The current default Date mapping behaviour](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#-result-type-mapping):

> TIMESTAMP and DATE columns are fetched as TIMESTAMP WITH LOCAL TIMEZONE using OCIDateTime. 

is different from the default Date handling behaviour of the [Joe Ferner driver](https://github.com/joeferner/node-oracle#dates).

I would like to disable mapping of Oracle `DATE`s to javascript dates completely, so that they would return `YYYY-MM-DD` strings which I could then convert myself.

Custom type parsers like in the [node-postgres](https://github.com/brianc/node-pg-types) driver would also be nice.

**Comment by bchr02** [comment]
You could use to_char(date_column, 'YYYY-MM-DD') to convert a date to a string in your desired format.

**Comment by hvrauhal** [comment]
That's what I'm doing at the moment, but it would be better to have it as an option in the driver instead of including it in every SELECT of a date column.

**Comment by cjbj** [comment]
Request noted. What kinds of things to you do with your own conversion? Are DATES the only datatype you want to have returnable as a string?

**Comment by rinie** [comment]
It would be nice to have the option for all datatypes to return as a string. Overflow and dataloss for large numbers seem horrible. Often It is just a chosen datatype in the table but not anything you want to use or calculate with in Javascript...

**Comment by cjbj** [comment]
@rinie one grand plan could be for node-oracledb to have a class that exposes Oracle number handling http://docs.oracle.com/database/121/LNOCI/oci19map003.htm#LNOCI185  This would be a lot of work.  It might also be overkill.  What do you think?

**Comment by hvrauhal** [comment]
The user-configurable conversions for dates, integers and numbers would fit my current use case. This would also allow you to leave the type conversion complexity out from the driver and push it down to libraries or application code.

**Comment by krismohan** [comment]
Can you please give some description of your app? Is it web based? One would think JS native types are most helpful, but yes, it depends on the application.

**Comment by hvrauhal** [comment]
JS native types are not helpful when for example number precision is important, or when dates could be considered in form "YYYY-MM-DD", or cast directly to for example moment.js. The original problem was, that the casting of Oracle DATE's to JS Date of this driver is different than that of the previous third party node-oracle driver.

**Comment by krismohan** [comment]
Yes, I see a value in having them as strings. Can you please elaborate on the cast issue? What is the other driver and what is the functional difference you are seeing in the JS Date values?

**Comment by hvrauhal** [comment]
`SELECT sessiontimezone, TO_DATE('01-JAN-2015') AS THE_DATE FROM DUAL`  and `JSON.stringify()`:ing the result rows gives the following results: 

Using OracleDB: 
```json
[{"SESSIONTIMEZONE":"+02:00","THE_DATE":"2014-12-31T22:00:00.000Z"}]
```

Using the Joe Ferner -driver:
```json
[{"SESSIONTIMEZONE":"+02:00","THE_DATE":"2015-01-01T00:00:00.000Z"}]
```

Code for the above is in: https://github.com/hvrauhal/oracle-driver-comparison

**Comment by rinie** [comment]
Full Oracle number handling would be overkill.
Important for me is that I can do roundtrips without any loss of precision.
So if I select some values from a row and insert them into another row the
data is 100% unmodified.
It is not that I don't like the current Result Type Mapping, but I don't
want the driver level to automatically round or modify data.
Perhaps an additional output format ARRAY_OF_STRINGS next to OBJECT, ARRAY
would suffice.
That combined with metadata and some javascript functions to be able to
perform the current result type mapping of the driver afterwards in the
application would be nice.

2015-02-16 18:44 GMT+01:00 Christopher Jones <notifications@github.com>:

> @rinie <https://github.com/rinie> one grand plan could be for
> node-oracledb to have a class that exposes Oracle number handling
> http://docs.oracle.com/database/121/LNOCI/oci19map003.htm#LNOCI185 This
> would be a lot of work. It might also be overkill. What do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oracle/node-oracledb/issues/20#issuecomment-74546384>.
>



-- 
Met vriendelijke groeten,
 Rinie Kervel.

Don't walk behind me, I may not lead.
Don't walk in front of me, I may not follow.
Just walk beside me and be my friend.

**Comment by cjbj** [comment]
@rinie other languages tend to allow per-column "define type" mapping (using OCI terminology http://docs.oracle.com/database/121/LNOCI/oci05bnd.htm#i421494 "the define step determines what data conversions must occur when data is returned to the application").   This would seem the most flexible solution.

**Comment by llambda** [comment]
Very much needed to use e.g. http://mathjs.org/ big numbers with DB Number type. JavaScript numbers are useless.

**Comment by cjbj** [comment]
@llambda do you currently use that math library with data from Oracle DB?  Do you also do maths in PL/SQL stored procedures?

**Comment by cjbj** [comment]
Here are several proposals floating around for how query columns could
be fetched in Node.js as strings.  Let us know if there is a
preference, or a better idea.

The discussion points are around ease of use vs flexibility, and
whether all queries or DB column types in an app will use the same
mapping.

Any type conversion will happen inside the Oracle C libraries, using
the same "define type" conversion semantics that other Oracle client
tools have.

Option 1: Per-application type-mappings for queries

Add a new top level fetchAsString attribute:

  oracledb.fetchAsString = [oracledb.NUMBER, oracledb.DATE];

This syntax says that all columns using dates (including timestamps)
and numbers (including things like binary_float) in any query will
have data returned as strings.

This syntax assumes that columns queried will only ever be returned in
native format (the default) or as strings (by using the new syntax).
Future, arbitrary type mapping isn't absolutely precluded, but that
would require additional syntax that wouldn't fit so nicely.

Option 2: Per-query type-mappings

Add a new fetchAsString attribute to execute() 'options'.  This could
be instead of, or in addition to Option 1.

This syntax says that all columns using dates (including timestamps)
and numbers (including things like binary_float) will have data
returned as strings.

 connection.execute(
   "SELECT mydate, mywhatever, mynumber FROM mytable",
   {}, // no binds
   {fetchAsString : [oracledb.NUMBER, oracledb.DATE]},
   function(err, result)
   { . . . }

Option 3: Per-column mappings in a query

Add a new fetchInfo attribute to execute() 'options'.

 connection.execute(
   "SELECT mydate, mywhatever, mynumber FROM mytable",
   {}, // no binds
   {fetchInfo : [ {type:oracledb.STRING}, {type:oracledb.DEFAULT}, {type:oracledb.STRING} ]},
   function(err, result)
   { . . . }

This says that the first and third columns will be fetched as strings.
The second column will be fetched in the default, native format.
Initially, the only valid values for each column are oracledb.STRING
and oracledb.DEFAULT.  In future, if warranted, the syntax could be
expanded to allow arbitrary mapping from the DB type to another type,
or allow other fetch attributes such as the max column size to be
returned.

**Comment by cjbj** [comment]
@rinie @bjouhier @wilkolazki @bchr02 @bigous and others: any thoughts on these design proposals for type mapping?

**Comment by hvrauhal** [comment]
@cjbj The per-query mappings are now achievable in the queries themselves with for example the `to_char` function. Option 1 of per application or per driver instance level configurability would be the simplest way to remove repetition from the application.

The query level configuration objects (Options 2 and 3) outside of the SQL could also be leveraged with a wrapper so they can be used to achieve the same goal and even more configurability.

So for me they all sound reasonable, provide solutions to the original problem, and complement each other.

**Comment by rinie** [comment]
Combination of Option 1 and 2 would be my preference.

**Comment by Bigous** [comment]
Hi people,

We have 2 questions here.

About the first one, I thing we should bring the result of Date just like Joe's in the example exposed by @hvrauhal . It's not natural ask for TO_DATE('01-JAN-2015') and receive 2014-12-31T22:00:00.000Z

About the second - preformat as string, now that is a dificult one.

In favor of doing things simpler, option 1. 
But thinking of it with the mind open, architecturaly speaking, it's a ECMAScript problem. It does not support numbers with large precision. So, I think that we should not put things in the driver that could potentially cause problems.

For example. Number with floating points in english use . (dot) to separate the decimal part, in portuguese use , (comma).

When using the native number type, the number is always a number.

Fixing the conversion to a single format of string can help with the localization problem, but will force everyone to convert 2x to show the information to the user.

So, I think we should let the programmer add the TO_CHAR to the fields that he needs to be with high precision not changing the driver, or use the 3rd option with a predefined combination of string format.

**Comment by rinie** [comment]
@Bigous in my application the javascript programmer and the query programmer are two different people. I do not want to mix them by modifying the query with TO_CHAR. Oracle separates the ., issue but in most programming languages it is the Englisch/American form internally.

**Comment by Bigous** [comment]
@rinie on the language itself it's almost always American English, but not when you are talking about strings. Specially when they are transfered between systems or displayed to the user. On those cases, languages and systems almost always have conversion and interpretation routines to do the job.

Oracle already does a very nice job on OCI with the session, instance, database and user NLS variables and custom types on languages that need to talk with the database. But as we all know, this is a lot of work and @cjbj came with 3 options to us to have a workarround faster.

I believe that the problem of precision and Date or Timestamp variables are in ECMAScript side, not on Oracle or OCI side.

That's why, in my opinion, the 3 option, is the nearest option to the solution itself (using the format condition only when it is needed). But the solution to me should be creating an OracleNumber, an OracleDate and an OracleTimestamp and not converting to string at all.

**Comment by bjouhier** [comment]
@cjbj. Thanks for putting me in the loop.

Option 1 is a _must_ for us and we would probably only use this one.
Option 2 is a _nice_to_have_ for people who want more flexibility at the query level.
Option 3 seems to be going a bit too far. If people want different columns to be treated differently I think that they should cast in SQL (`TO_CHAR(col)`) rather than through API.

I'm unsure about @hvrauhal's `TO_DATE('01-JAN-2015')` case. On the one hand, I prefer that dates be interpreted as GMT because this is what we usually want on a server. On the other hand it looks like most drivers (including JDBC) interpret them in the local timezone. To me this looks like a (historical) bias which favors client server apps (where you want minimal work to display data) against 3-tier apps (where you usually want a timezone-neutral interpretation). 

An` oracledb.fetchAsGMT = true/false` setting would solve the problem (option 1/must, 2/nice-to-have, same as above).

**Comment by bjouhier** [comment]
@Bigous by default values should be formatted using language-neutral formats. This means no thousand separators and dot as a decimal point for numbers and ISO 8601 for dates. There is no ambiguity.

There could be an option to format in a the session's locale but IMO it should be at least off by default and I would not even implement it to keep things sane and simple.

Exposing Oracle driver types (OracleNumber, OracleDate, ...) solves the problem but it complicates typical use from JS. The first thing most people will w

**Comment by Bigous** [comment]
@bjouhier That was exactely what I was talking about when I wrote about predefined combination of string format.

But the goal should be the oracle data types just like all other oracle drivers do.

I cannot see more complication or performance problems on this over transform it into a string type and doing magic to calculate things, or converting it back, or even working always as string. In fact, I can see just the oposite. But this is another argumentation.

**Comment by bjouhier** [comment]
Our needs are the following:

* we want to be able to transform decimal value into our own Decimal objects. If we get the value as a string we can do it (any decimal type should be constructible from string). 
* we want to get dates and timestamps in GMT and get them as JavaScript Date objects. 
* we want to get small Blobs as JS strings and small Clobs as node Buffers.
* we want to get large Blobs/Clobs as streams of strings/Buffers (or readable in chunks through some kind of `read(callback)` API).

@Bigous 
Unless you have decided to implement your logic around Oracle driver types, the Oracle types won't get you very far. For example, if decimals were returned as instances of `OracleNumber`, we would just call `toString()` on them to convert them to our own decimal type. And applications that don't care much about precision (not everyone does accounting) will be happy to just get the values as JavaScript numbers (IEEE double).

@cjbj 
To make the mapping more versatile, we could use a mappings object like:
```javascript
oracledb.typeMappings = {
  NUMBER: "number", // or "string" (or "OracleNumber"?)
  DATE: "date", // or "string" (or "OracleDate"?)
};
```
A type mapping could be either a simple string (when we only need to specify the JS type), or a small object if we want to pass several options. For example
```javascript
  DATE: {
    type: "date",
    gmt: true,
  }
```
Types that would not have any entry in `oracledb.typeMappings` would get the default mapping.

One advantage of this API is that it is easy to extend. New mapping options would not require new `oracledb.xxx` properties, just optional keys in the type mappings.

But I may be splitting hairs here. For us, what matters is that we be able to do the mappings that I described above.

**Comment by rinie** [comment]
@bjouhier +1: your mapping object has a nice syntax. Splitting hairs about GMT: probably UTC but generally I would think: just use the database time, no timezone mapping?

**Comment by bjouhier** [comment]
@rinie +1 on UTC.

Regarding timezone, I would distinguish three cases:
* if the column type is `TIMESTAMP WITH TIME ZONE` each value carries its timezone. There is no ambiguity about the UTC value of such timestamps. We have 2 choices here: 1) we convert to JS Date, and in this case we lose the timezone info, 2) we convert to a small object which combines a JS Date, a timezone offset and a timezone region name.
* if the column type is `TIMESTAMP WITH LOCAL TIME ZONE`, all values are expressed in the server's timezone. There is no ambiguity either about the UTC value of such timestamps. So we can return them as a JS Date.
* otherwise (DATE, TIMESTAMP types), there is an ambiguity because the values are not locked to a any specific timezone. In this case I would return the value as JS Date and I could provide 3 options to interpret the value: 1) as a value in the server's timezone, 2) as a value in the client's timezone, 3) as a UTC value.

So maybe something like:
``` javascript
    DATE: {
        type: "date",
        tz: "server", // or "client" or "utc"
    }
```
And I would introduce a type called "dateWithTimezone" which would cause the value to be returned as a small object containing date + tz offset + tz name. To get this mapping just use:
``` javascript
    TIMESTAMP: "dateWithTimezone"
```

**Comment by bjouhier** [comment]
Small correction: what I said about us wanting the date and timestamps to be interpreted as UTC is a bit wrong. What we want is that they be interpreted as values in the server's timezone (which in our case will be UTC), so that computations done with SQL expressions are consistent with computations done in JS.

So the default should be that date and timestamps be interpreted in the server (database) timezone.

**Comment by Bigous** [comment]
@bjouhier +1 for mapping configurable globaly or in query/column mapping. but...

> Unless you have decided to implement your logic around Oracle driver types, the Oracle types won't get you very far.

Our systems are havyly based on Oracle technology. And when you start to work with advanced features in Oracle, you do use Oracle Types or you start tons of working in useless conversions.

>For example, if decimals were returned as instances of OracleNumber, we would just call toString() on them to convert them to our own decimal type. And applications that don't care much about precision (not everyone does accounting) will be happy to just get the values as JavaScript numbers (IEEE double)

That's why I voted in favor of configuration on column mapping (the 3rd option). Because most of the time we will not need any mapping at all.

>we want to get small Blobs as JS strings and small Clobs as node Buffers.
we want to get large Blobs/Clobs as streams of strings/Buffers (or readable in chunks through some kind of read(callback) API).

I think you mean just the oposite here - BLOBs to Buffer and CLOBs to String.

>And I would introduce a type called "dateWithTimezone" which would cause the value to be returned as a small object containing date + tz offset + tz name.

It seems to me that you have just started making an OracleTimestamp object...

**Comment by bjouhier** [comment]
@Bigous Good catch on blob/clob.

Our app works with several DB engines. This explains why we want to convert to JS types as early as possible.

**Comment by cjbj** [comment]
Lot's of good discussion here; thanks everyone. 
One other thing to throw in the mix is that we need a way for queries on Oracle 12c JSON columns (i.e. LOBs or VARCHARs) to return the data as either string/buffer values, or converted to JSON objects. At a guess, you would want to do this per-query, since many VARCHARs or LOBs will not contain JSON.

**Comment by Bigous** [comment]
Well :D I already think that every mapping should be per columns, so, to me yes.

**Comment by bjouhier** [comment]
@cjbj For us, it won't make much difference if the driver parses JSON values and returns them as objects, or if it hands it off to us as strings and we do the parsing. Except if the driver can optimize and parse faster than `JSON.parse`.

**Comment by cjbj** [comment]
@bjouhier good point about performance

**Comment by llambda** [comment]
@cjbj Yes, and the BigNumber constructor would take a String representing the Number type in Oracle. E.g.

```
var BigNumber = require('bignumber.js');
var y = y = BigNumber('123456.7e-3')
```

Since Oracle Number can be much larger than JavaScript's numbers.

**Comment by bjouhier** [comment]
Coming back to the original question, the problem can be fixed by executing `ALTER SESSION SET TIME_ZONE='00:00'` after each connection. Then do we really need fancy date type mappings to solve this? See #154.

**Comment by cjbj** [comment]
@bjouhier the question is what should the default be? I'm meeting some internal resistance to change, so yell out with more arguments.

An ALTER SESSION will generate a round trip, which isn't optimal.

**Comment by bjouhier** [comment]
Well, the roundtrip is not an issue for us because we have our own pool (our code is designed for several DB engines and all drivers don't all have a pool). We only execute the `ALTER SESSION` when we allocate a new native connection for our pool.

What about introducing an `initConnection` callback (or event) in your pool. This would give people a hook to initialize connections when they get allocated by the pool rather than every time they get requested from the pool.

Given this, I would keep the default as it is because this is very flexible. If something can be done efficiently (and in a sticky way) through SQL, why introduce a special API? (but take this with a pinch of salt, I tend to be an API minimalist).

On the other hand, #154 should be fixed because it is important to give people a _natural_ timezone setting (with daylight savings on) by default.

**Comment by bjouhier** [comment]
Given my last comment in #154 I would suggest that:

1. dates get interpreted according to the SESSION TIMEZONE setting. If this timezone is `00:00`dates will be returned in UTC, if it is `Europe/Paris` they will be returned as local dates (with DST).
2. the SESSION TIMEZONE should be set to `00:00` by default (when connections are allocated by the pool), to avoid the problem discussed in #154.

If we give people two knobs to control this (SQL SESSION TIMEZONE and type mapping) type mapping should win. But aren't we looking for trouble here? I'd rather keep it simple and have dates returned according to the SESSION TIMEZONE. If people aren't happy with the dates they are getting and don't feel like tweaking SESSION TIMEZONE in SQL they can still tweak them in JavaScript, so we are really talking about a 3rd knob here.

**Comment by cjbj** [comment]
@bjouhier if I read your various posts correctly, your conclusion is to suggest leaving date handling unchanged (and introduce type mapping).  Is this interpretation correct?

**Comment by bjouhier** [comment]
@cjbj Almost. More precisely:

* dates and timestamps are interpreted in the SESSION TIMEZONE, except TIMESTAMP WITH TIMEZONE for which there is no ambiguity (because the column stores the TZ). I think that this is the current behavior.
* it is the developer's responsibility to alter the SESSION TIMEZONE after allocating connections. To avoid a roundtrip every time a connection is obtained from the pool it would be nice to have a pool event to initialize the timezone on fresh connections.
* the default SESSION TIMEZONE setting (if the developer does not alter it explicitly) should be '00:00'. This is a difference with today's behavior.
* type mapping should not try to interfere with SESSION TIMEZONE and re-interpret dates. On the other hand there should be an option to obtain a small object with` { date: the_js_date, timezone: tz_offset_and_name }`  instead of a JS date, so that we can retrieve all the info when the column is TIMESTAMP WITH TIMEZONE.

**Comment by Bigous** [comment]
I agree with @bjouhier except for this part:

> the default SESSION TIMEZONE setting (if the developer does not alter it explicitly) should be '00:00'. This is a difference with today's behavior

I think that Oracle defaults behavior should not be changed.

**Comment by cjbj** [comment]
An update: we are not planning on changing how dates & timestamps are natively handled for 1.0.  We will continue to review how dates are used and how the upcoming type mapping feature is adopted; there is more work for us to do with dates & timestamps.

@bjouhier You have good ideas. Regarding changing time zones for new connections, are you using more than one time zone in your apps?

**Comment by bjouhier** [comment]
@cjbj The timezone change is rather an academic argument for me. We are setting up all our connections in UTC. As we have our own pool (on top of the driver), we only need to set it when we grow the pool. 

Q: what happens if you execute an ALTER SESSION and then return the connection to the driver's pool? Will the next one who gets this connection from the pool get impacted? (again, academic question).

**Comment by cjbj** [comment]
@bjouhier a session's settings are persistent - but the session may close when the pool shrinks and  newly created sessions will again have default settings.

**Comment by bjouhier** [comment]
@cjbj That's why I was suggesting an API to get an event when a fresh connection gets created by the pool. By putting the session initialization code in this event handler you save the overhead of re-executing this code (server roundtrips) every time a session is retrieved from the pool.

**Comment by cjbj** [comment]
@bjouhier I noted the point as it's an interesting thought.   What can/can't be done internally needs some investigation.

**Comment by Bigous** [comment]
> Q: what happens if you execute an ALTER SESSION and then return the connection to the driver's pool? Will the next one who gets this connection from the pool get impacted? (again, academic question).

Will! We do it in Java with the thin client from Oracle.

**Comment by cjbj** [comment]
Try the new `fetchAsString` and `fetchInfo` options in node-oracledb 1.0
See https://github.com/oracle/node-oracledb/blob/master/doc/api.md#typemap

I'm going to leave this issue open so we can continue discussing date handling here.

**Comment by cjbj** [comment]
It's time to close this, pardon the pun.
