### ISSUE TITLE
example using 'long raw' type column

### ISSUE THREAD

**Issue by sukjin** [oracle/node-oracledb#218]
I read that 'blobhttp.js' and 'blobinsert1.js' in Example folder.

I tried it and work good.

but my oracle table's column is 'long raw' type.

I changed something on the 'blobhttp.js' and 'blobinsert1.js' 

but it didn't work.

how can I do 'INSERT' my JPG file in the 'long raw' type?

**Comment by cjbj** [comment]
There's no native support for LONG RAW in node-oracledb 1.1. Perhaps try using a staging table with a blob column and use something like https://community.oracle.com/thread/15723 ?

**Comment by ksachdeva** [comment]
Is the support for 'LONG RAW' type planned in future releases ? - thanks

**Comment by cjbj** [comment]
@ksachdeva it's one of many things on our list.  What's your use case?

**Comment by ksachdeva** [comment]
Use case is that I have a column with LONG RAW type. The table was created using grails/gorm. I am writing a nodejs based client that retrieves this column and got stuck today because of type. oracledb nicely informed that it is not supported instead of throwing strange error which is very good. Have searched on web and understand that this type has been deprecated and there are methods to transform from LONG RAW to BLOB but unfortunately the database in question belongs to another organization so does not have much say and the fact that it is a production database with lot of data it would be difficult to have the type changed on the database itself.

**Comment by cjbj** [comment]
I can see having LONG RAW support would be useful for you.

**Comment by cjbj** [comment]
node-oracledb v2 now supports LONG and LONG RAW, fetched as String and Buffer respectively. See https://blogs.oracle.com/opal/node-oracledb-2013-development-is-now-on-github and check the doc for details.
