### ISSUE TITLE
Error Reason: image not found

### ISSUE THREAD

**Issue by randomailer** [oracle/node-oracledb#247]
Error when I trying to start app from Intellij Idea

```
Error: dlopen(/Users/..../projects/admin-platform/node_modules/oracledb/build/Release/oracledb.node, 1): Library not loaded: /ade/b/3071542110/oracle/rdbms/lib/libclntsh.dylib.11.1
  Referenced from: /Users/..../projects/admin-platform/node_modules/oracledb/build/Release/oracledb.node
  Reason: image not found
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by cjbj** [comment]
You'll need to set DYLD_LIBRARY_PATH so that the IDE passes it to node-oracledb or
look at https://github.com/oracle/node-oracledb/issues/231 and https://github.com/oracle/node-oracledb/issues/149

**Comment by derickbailey** [comment]
@cjbj is it true that the DYLD_LIBRARY_PATH must be set, still? I've been reading the other linked threads (231 and 149) and i'm a bit confused.

I'm having problems with OSX 10.11 / El Capitan, with launchers like nodemon and foreverjs. they don't work, because OSX won't foward the DYLD_LIBRARY_PATH environment variable.

I have the DYLD set in my .bash_profile appropriately, so I can run my code by doing `node foo.js` but if i change this to `nodemon foo.js` it fails with the "Reason: Image Not Found" problem since the DYLD path is not forwarded. 

Is there a way to make this work with nodemon, foreverjs, and other sub-shell / launchers?

**Comment by cjbj** [comment]
@derickbailey I documented a method of installing with 11.2 instant client that doesn't require DYLD_LIBRARY_PATH.  Try it out: https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instosx

**Comment by derickbailey** [comment]
thanks @cjbj - i had not noticed the change in those instructions when i looked at it before. i re-ran all of the steps, and everything is working for me, with nodemon and my other tooling now.

**Comment by cjbj** [comment]
@derickbailey you could alternatively create the links in ~/lib as noted by @raymondfeng in https://github.com/oracle/node-oracledb/issues/149#issuecomment-170711705
I will update INSTALL.md to show both methods.  I have already updated the generic OS X Instant Client install notes at http://www.oracle.com/technetwork/topics/intel-macsoft-096467.html#ic_osx_inst

**Comment by jeffersongouveia** [comment]
For me it did not work set the DYLD_LIBRARY_PATH, but LD_LIBRARY_PATH worked fine.

e.g: LD_LIBRARY_PATH=/Users/<username>/Library/Oracle/instantclient_12_2/
