### ISSUE TITLE
Support ldap connections

### ISSUE THREAD

**Issue by joe-adams** [oracle/node-oracledb#287]
It would be nice if ldap or jdbc connection strings were supported.  As far as I can tell this module cannot be used if you need to use ldap to connect to your database.

**Comment by cjbj** [comment]
LDAP is supported, just not the JDBC connection string format.  http://stackoverflow.com/questions/31994159/how-do-you-connect-to-an-ldap-server-using-node-oracledb

I had already noted the interest in this area.  Since it is dependent on changes to the underlying OCI and the Oracle Net layers I'm going to close this issue since there is no node-oracledb specific change needed.

**Comment by cjbj** [comment]
Actually closing per my last comment.

**Comment by omaksi** [comment]
I also have an issue with connecting using LDAP. I have ldap.ora and sqlnet.ora configured, I can connect to Oracle using the LDAP alias using Toad or SQL Nav, but when trying to use node-oracledb I get ORA-12154.

Is there anything extra required for the connectString except for the LDAP alias?

**Comment by cjbj** [comment]
No. Node-oracledb is just an OCI client (e.g. like SQL*Plus, PHP OCI8, Python cx_Oracle etc).
Please open a new issue for new questions - thanks.
