### ISSUE TITLE
Mac: node index.js works but not npm start

### ISSUE THREAD

**Issue by anthonylai** [oracle/node-oracledb#444]
Hi,

  I have installed oracledb and using it on a mac with node 5.7.0.  In the code, if I do a require on oracledb:

const Oracledb = require('oracledb');

  With the addition of this line:
1.  'node index.js' still works as expected
2.  'npm start' throws segmentation fault 11, and no output comes from npm-debug.log

  The odd thing is this is the start script, which simple is executing 'node index.js'.

drilldown$ npm start
  "scripts": {
    "start": "node index.js"
}

drilldown$ npm start

> drilldown@1.0.0 start /Users/aslai/dev/ux/drilldown
> node index.js

Segmentation fault: 11

Please kindly assist, as other tools like forever would fail with the same issue.

**Comment by cjbj** [comment]
There's not a lot of info given. 

 For a start, try the new 12.1 Instant Client on OS X (see https://github.com/oracle/node-oracledb/issues/440  Follow the install instructions at http://www.oracle.com/technetwork/topics/intel-macsoft-096467.html#ic_osx_inst because there hasn't been a node-oracledb release with updated instructions)

**Comment by cjbj** [comment]
Closing due to lack of feedback.
