### ISSUE TITLE
Array binding for query "WHERE IN" clause not working

### ISSUE THREAD

**Issue by CorvusCorrax** [oracle/node-oracledb#450]
when using an array in a SQL IN binding, no row is returned,
when using an integer a row is returned
```
var oracledb = require('oracledb');
oracledb.getConnection({...}, function(err, connection) {
  connection.execute('SELECT * FROM TEST WHERE IDTEST IN (:1)', [[4, 5, 6]], {}, function(err, result) {
    console.log(result);
  });
});
```
does node oracledb support it ?

**Comment by dmcghan** [comment]
Have a look at this:
https://github.com/oracle/node-oracledb/issues/137

Does that help?

**Comment by atiertant** [comment]
well as sql query are limited to 64k, use a binding for all element of an array or stringify them will increase query size quickly !

**Comment by cjbj** [comment]
There are various solutions depending on the need; security is always the issue to be careful with, with performance next. For fixed or a capped number of binds, just use a statement with the max number of binds in the IN clause and bind NULLs to anything the actual invocation doesn't want to specify.  At the other extreme put the values in some temporary table and don't use IN.  There are plenty of web references with solutions and discussions.  It's really outside the scope of node-oracledb since it is fundamental Oracle bind & SQL behavior. Note [AskTom has one solution](https://asktom.oracle.com/pls/asktom/f?p=100:11:0::::P11_QUESTION_ID:110612348061) similar to [Dan's](https://github.com/oracle/node-oracledb/issues/137#issuecomment-120036280) but doesn't need the APEX gunk. 

Nitpick: From AskTom "[Even in Oracle8, 64k was not the limit."](https://asktom.oracle.com/pls/asktom/f?p=100:11:0%3A%3A%3A%3AP11_QUESTION_ID:41742083561301)"  Also see the note in [Logical Database Limits](
http://docs.oracle.com/database/121/REFRN/GUID-685230CF-63F5-4C5A-B8B0-037C566BDA76.htm) "The limit on how long a SQL statement can be depends on many factors, including database configuration, disk space, and memory"

**Comment by liu-minjie** [comment]
how node-mysql solve this problem ?

**Comment by dmcghan** [comment]
@liu-minjie What makes you think they have? A link would help...

**Comment by lmcarreiro** [comment]
I've created a [tagged template literal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) `sql` to write my SQL queries.


### Example:

```ts
const query1 = sql`select * from table where a in (${[1, 2, 3]})`

query1 === {
  query: "select * from table where a in (:0, :1, :2)",
  parameters:[1,2,3]
}

const query2 = sql`
  select *
  from table
  where name like ${'some str'}
    and a in (${[1, 2, 3]})
    and b = ${100}
    and c in (${['val1', 'val2']})
`

query2 === {
  query: "select * from table where name like :0 and a in (:1, :2, :3) and b = :4 and c in (:3, :4)",
  parameters: ["some str", 1, 2, 3, 100, "val1", "val2"]
}

const [result1, result2] = await Promise.all([
  connection.execute(query1.query, query1.parameters),
  connection.execute(query2.query, query2.parameters)
])
```


Source code: https://stackoverflow.com/a/57614632/4871582

**Comment by cjbj** [comment]
Cross referencing to the related comment: https://github.com/oracle/node-oracledb/issues/699#issuecomment-524018809
