### ISSUE TITLE
Instant Client Redistribution

### ISSUE THREAD

**Issue by metavine** [oracle/node-oracledb#455]
This is not really an issue, however I wonder if anyone can help me with the legality of redistribution of the instant client for the use of our node package distribution which depends on the Node.js oracledb  addon. We are just trying to make things as much as easy for our client to do the package installation.

By looking at the license, it seems it is OK to do if all terms are complied, but I just try to confirm.

Any help will be much appreciated.

**Comment by bchr02** [comment]
You might want to check out: https://github.com/bchr02/instantclient

It's an npm package for downloading instantclient directly from Oracle, so that way you don't need to redistribute.

But to directly answer your question, I found this on the Oracle [Instant Client download page](http://www.oracle.com/technetwork/database/features/instant-client/index-097480.html):


> Please note that Instant Client is provided under a separate [OTN Development and Distribution License for Instant Client](http://www.oracle.com/technetwork/licenses/instant-client-lic-152016.html) that allows most licensees to download, redistribute, and deploy in production environments, without charge.  Please consult the license and your legal department for clarification, if necessary.

Regardless, I think some kind of confirmation from someone directly at Oracle would still be helpful to you.

**Comment by metavine** [comment]
Hi @bchr02 , thank you very much for your help and your work for the instant-client node module. I think the most difficult part is to ask the end user to create an OTN account, and come back to the installation to fill in all the details. It is trivial enough for the developer to do so, but it is not quite simple for people who try to use our (or anyone else's) package that depends on the instant client.

**Comment by cjbj** [comment]
@metavine you need to check with your own Legal people to review the wording in the license.  IANAL and can't comment.
