### ISSUE TITLE
More details for NJS-037.

### ISSUE THREAD

**Issue by hariprasadkulkarni** [oracle/node-oracledb#469]
I am invoking a PLSQL procedure which takes a bunch of inputs. Many of them are arrays of STRING, NUMBER and DATE types.

I'm creating a binding for these values before sending them to the procedure. I'm following the examples given here - https://github.com/oracle/node-oracledb/blob/master/examples/plsqlarray.js

I get an NJS-037 error. The message I get is this `incompatible type of value provided`.

From this, all I can conclude is that I'm sending an incompatible value for a certain type. But I don't know for which one. 

Is there a way to get the details? Or a debug flag that I can enable to get the sql that is finally executed?

**Comment by cjbj** [comment]
The advantage of open source is you can track this error back to the [source](https://github.com/oracle/node-oracledb/blob/master/src/njs/src/njsMessages.cpp#L76) and then see where `errIncompatibleTypeArrayBind` is used, which is [here](https://github.com/oracle/node-oracledb/blob/master/src/njs/src/njsConnection.cpp#L1163) and [here](https://github.com/oracle/node-oracledb/blob/master/src/njs/src/njsConnection.cpp#L1181). 

Looks like your arrays don't contain what you think they do.  Start cutting down the testcase until you identify the problem.  Or build up from a simple case and add complexity until it reaches your desired PL/SQL call.

Yes, the error handling can be improved.  We can add that to the task list.

Re the SQL statement, since you are using bind variables, the final statement is the same as the one you entered: there is no substitution of values into the statement text.

**Comment by hariprasadkulkarni** [comment]
> Start cutting down the testcase until you identify the problem.

There are many variables. I was wondering if there is a better way to debug that. 

If I change the code in the cpp driver, I'll need to build it and install it to test. Is there a link which describes the build and install steps? 

If I end up generating a helpful error message, I can send a PR.

**Comment by cjbj** [comment]
A PR would be great.  Read [CONTRIBUTING](https://github.com/oracle/node-oracledb/blob/master/CONTRIBUTING.md) first, though.  Installation from a GitHub clone is the [same as from NPM](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md), you just need to specify the directory where you cloned this repo.  Set up your environment and then run:

```
npm install ./node-oracledb
```

**Comment by cjbj** [comment]
Closing this since the PR was opened.
