### ISSUE TITLE
Recommended solution for automatic installation in a CI environment?

### ISSUE THREAD

**Issue by jmfee-usgs** [oracle/node-oracledb#480]
What is the recommended solution for automatic installation in a CI environment?

I'm trying to add this project as npm dependency for an application that uses Travis CI.  The instant client and express edition RPMs appear to require a manual download and installation, making automation difficult.

**Comment by sagiegurari** [comment]
I wrote a library that extends oracledb and i faced same issue.
The wrapper is at:
https://github.com/sagiegurari/simple-oracledb
I'll start with the bottom line, it is very problematic and my library in the travis build does NOT install oracledb and runs tests against mock that i wrote.
So tests are running fast and I am able to also simulate error scenarios that with a normal DB might be an issue (for example an error while reading a CLOB and so on...).
HOWEVER, you still must test against a real DB every once and a while, so for that I created a different build which is using docker.
I have 1 docker image that is running oracle and another docker image that installs my project + oracledb + mocha and I run only an integrative test there.
It is no CI as it is not triggered every time i push code to simple-oracledb, but I don't need it as a CI since most of the times, my tests do a better job and I only run it manually when either i do a big functionality change or if oracledb have released a new version.
You can checkout the docker build at:
https://github.com/sagiegurari/misc-test/tree/oracle-docker
I didn't want that the docker build would be my CI because
* I lose all the capabilities travis is giving me (testing with different node versions for example).
* build is longer
* less stable (timing issues sometimes if tests start before oracle finished loading).

**Comment by jmfee-usgs** [comment]
Here's my current workaround, let me know if there are more preferred alternatives:

1) add oracledb to project as _optional_ dependency:
```
npm install --save-optional oracledb
```

2) wrap requires in try/catch
```
try {
  oracledb = require('oracledb');
} catch (e) {
  oracledb = null;
}
```

3) use a custom getConnection method
```
factory.getConnection = function (options) {
    if (oracledb === null) {
      return Promise.reject(new Error('oracledb not installed'));
    } else {
      return oracledb.getConnection(options);
    }
```

4) stub the getConnection method for unit testing

**Comment by jmfee-usgs** [comment]
Closing for now since I came up with a workaround.

Would be more convenient if the instant client was _actually_ instant.
