### ISSUE TITLE
Make it compatible with Travis CI

### ISSUE THREAD

**Issue by atiertant** [oracle/node-oracledb#503]
We use node-oracledb in projects using Travis Ci for their tests but interactive license agreement of instantclient and the OTN login / password doesn't let us securely install node-oracledb in github/Travis CI.

**Comment by atiertant** [comment]
https://github.com/oracle/node-oracledb/issues/3

**Comment by cjbj** [comment]
Hi @atiertant This is outside the scope of node-oracledb.  It's a 'known thing' and being looked at so I will close this issue, if that's OK?

**Comment by kwent** [comment]
Hi @cjbj ,

With the new version and precompiled library for Linux for example. does that make installation of `oracledb` much easier ? If yes would you mind documenting an example on a simple `ubuntu14.04/16.04` ? I think that would help a lot !

Regards

**Comment by cjbj** [comment]
@kwent Installation is a lot easier and faster for almost everyone.  

The [Linux Instant Client ZIP instructions](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instzip) work fine on Ubuntu 17.10.  Make sure you install libaio1, as noted.  If the Ubuntu 14.04/16.04 glibc is too old for the pre-built binaries, then follow the [steps to build from source](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#github): this is also easier then v1, since you don't need Oracle SDK and don't need to set related environment variables before compiling.
