### ISSUE TITLE
Store procedure - Custom type not accepting,

### ISSUE THREAD

**Issue by shashikantdoke** [oracle/node-oracledb#508]
Below is the sample Store procedure:

create or replace 
PROCEDURE        ABC (
i_test_cust_id_arr           IN  TYP_A,
i_test_product_class_arr     IN  TYP_B,
i_test_amt_arr               IN  TYP_C,
i_test_wf_status_arr         IN  TYP_D,
i_test_cha_code_arr          IN  TYP_E,
o_error_code                OUT NUMBER,
o_error_msg                 OUT VARCHAR2) AS
BEGIN
--
END;

Custom Type definition is :- 
create or replace 
TYPE        TYP_A AS TABLE OF VARCHAR2(14);

While executing the above stored procedure  through this node module, we are getting below error:
PLS-00306: wrong number or types of arguments in call to 'ABC'.

Pls refer below code snippet :-
var bindvars = {
                i_test_cust_id_arr: {
                    val: ['15201'],
                    type: oracledb.STRING,
                    dir: oracledb.BIND_IN
                }, o_error_code: {
                    type: oracledb.NUMBER,
                    dir: oracledb.BIND_OUT
                },o_error_msg: {
                    type: oracledb.STRING,
                    dir: oracledb.BIND_OUT
                }				
            };
var sp ="BEGIN ABC(:i_test_cust_id_arr,:o_error_code,:o_error_msg); END;";
connection.execute(sp,bindvars,...);

Please provide solution on this.

**Comment by dmcghan** [comment]
@shashikantdoke The data type you have defined is a Nested Table type. The data type [currently supported](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#plsqlindexbybinds) for arrays is the Associative Array type (a.k.a. Index By type due to its syntax). The syntax for creating them is very similar, but their usage varies some.

Here's the type you've defined (nested table):
```sql
create or replace type type_a
as table of varchar2(14);
```

And here's the equivalent as an associative array:
```sql
create or replace type type_a
as table of varchar2(14)
index by pls_integer;
```

Here's a series on array/collection types in PL/SQL if you're interested in learning more:
https://www.youtube.com/playlist?list=PL0mkplxCP4yizj8BnM9MxJRxJqKvbmwXS

**Comment by cjbj** [comment]
See https://github.com/oracle/node-oracledb/issues/147

**Comment by shashikantdoke** [comment]
Than you very much..with this given solution, I have resolved my issue..
