### ISSUE TITLE
ORA-01007: variable not in select list

### ISSUE THREAD

**Issue by CorvusCorrax** [oracle/node-oracledb#525]
On Fedora 23 with node 6.2.1, node-oracledb 1.11.0 and Instant Client 12.1

```
var oracledb = require('oracledb');

var config = {
  user          : 'user',
  password      : 'secret',
  connectString : 'host/database'
};

oracledb.getConnection(config, function(err, connection) {
  if (err) {
    throw err;
  }
  connection.execute("CREATE TABLE TESTORACLE (FIRST_NAME VARCHAR(255), LAST_NAME VARCHAR(255))", function(err, result) {
    if (err) {
      throw err;
    }
    console.log('CREATE : ', result);
    connection.execute("SELECT * FROM TESTORACLE", function(err, result) {
      if (err) {
        throw err;
      }
      console.log('FIRST SELECT : ', result);

      connection.execute('ALTER TABLE TESTORACLE DROP ("FIRST_NAME")', function(err, result) {
        if (err) {
          throw err;
        }
        console.log('DROP : ', result);

        connection.execute("SELECT * FROM TESTORACLE", function(err, result) {
          if (err) {
            throw err;
          }
          console.log('SECOND SELECT : ', result);
        });
      });
    });
  });
});
```
Returns 
```
CREATE :  { rowsAffected: 0,
  outBinds: undefined,
  rows: undefined,
  metaData: undefined }
FIRST SELECT :  { rows: [],
  resultSet: undefined,
  outBinds: undefined,
  rowsAffected: undefined,
  metaData: [ { name: 'FIRST_NAME' }, { name: 'LAST_NAME' } ] }
DROP :  { rowsAffected: 0,
  outBinds: undefined,
  rows: undefined,
  metaData: undefined }
/home/dev/svn/oracleTest/knex/testOracledb.js:37
                  throw err;
                  ^

Error: ORA-01007: variable not in select list

    at Error (native)
```

**Comment by dmcghan** [comment]
@CorvusCorrax The issue you're running into is related to the [Statement Cache](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#stmtcache).

You can disable the cache by setting stmtCacheSize to 0 in your config for `getConnection` or you can explicitly reference column names. I'd recommend explicitly referencing column names except in the case of one-off scripts (which your example mimics).

**Comment by atiertant** [comment]
@dmcghan is it possible to flush the cache after an alter?

**Comment by dmcghan** [comment]
@atiertant There is no API to do this currently. @cjbj would have to chime to indicate if it's possible and something worth considering for the future.

Are you unable to use column names explicitly?

**Comment by cjbj** [comment]
Generally cache issues like this are only seen during development where disabling the statement cache is an acceptable and perfectly good solution. There was a suggestion in #182 to allow particular statements not to be cached.  Is the added API complexity worth it?

Note referencing column names may not solve every occurrence, if a column type changes.

**Comment by atiertant** [comment]
@dmcghan as you know we work on knex integration and no other supported dialect got this kind of problems...so to be compatible we need get this to work...

an other problem is the error message, it takes us 2 days to understand why a `select * from "table"` crash the tests and reproduce the bug...

@cjbj your right "Generally" this could be done, in our case we can disable cache during tests but knex is integrate many orm...orm generate table and structure, migrations...
if you allow particular statements not to be cached, this will not solve your problem because we can't know if the user will alter table later...

would it be possible to flush all cache related to a table or full cache, ...? so we could do it after an alter table in our case or after the particular statements in #182 without changing execute() API

**Comment by cjbj** [comment]
There have been various discussions about this.  The real solution is cache invalidation: any statement cache (in any process, on any machine) referencing a changed DB object would need to be flushed.  This would need to be done by OCI.  I first raised this several years ago....
I expect the historic design ethos was that production systems don't change DB objects at runtime.

We'll look at mitigations in node-oracledb but there won't be a 100% transparent solution since there can't be any process interaction.

[For future searchers: ORA-00932 is also a symptom of the statement cache being out of date]

**Comment by cjbj** [comment]
The ODPI-C layer used by node-oracledb v2 has some 'smarts' about this, and will internally re-execute if it sees an ORA-1007.   See https://github.com/oracle/odpi/blob/c843d7f5e2556f12dae13e0ee097a443308ef9d4/src/dpiStmt.c#L534-L546
