### ISSUE TITLE
ORA-24418 Cannot open further sessions.

### ISSUE THREAD

**Issue by Foxprodev** [oracle/node-oracledb#550]
Hi!
Yes, I' am getting ORA-24418 too.
`queueRequests: true`
It began from  1-8 errors in a row and ended as ORA-24418 lock. (about 2 weeks period)
Code is here: [https://gist.github.com/Foxprodev/bf9375c299cb426c4507e71d881449fa](https://gist.github.com/Foxprodev/bf9375c299cb426c4507e71d881449fa)
Each time ORA-24418 appears: 
- connections in use : 30
- connections open : 30

Then `connections in use` decreases, but `connections open` strangely not.
Looks like I'am stacked.
P.S. Logs size is too big, sorry.

**Comment by dmcghan** [comment]
@Foxprodev I'm not sure why you're getting ORA-24418... But here are some suggestions anyway.

Change your `async.each` calls to `async.eachSeries`. A connection can only do one thing at a time anyway. 

I'd also recommend _not_ using autoCommit for each execution. You have valid transactions. Use a counter add autoCommit: true to the options object of the last execution of the series.

Finally, the date logic sysdate - 3/24 looks a little strange. What time zone is your database's OS using and what time zone is - 3/24 going to? 

I know they are long, but have a look at [this post on dates](https://jsao.io/2016/08/working-with-dates-in-javascript-json-and-oracle-database/) and [this one](https://jsao.io/2016/09/working-with-dates-using-the-nodejs-driver/) more specifically related to Node.js.

**Comment by Foxprodev** [comment]
@dmcghan, sysdate returns UTC+3, thats why I use sysdate-3/24 to save in UTC

**Comment by dmcghan** [comment]
@Foxprodev Let us know if the other suggestions fix the problem you're experiencing. 

Also, I'd recommend using the following: `systimestamp at time zone 'utc'`

It's a bit more readable, portable, and safe (works if someone changes the OS time zone). Since the column is a DATE, the data type will scale down fine. 

Another option is to [set the `sessiontimezone` to UTC](https://jsao.io/2016/09/working-with-dates-using-the-nodejs-driver/#explicitly-setting-the-session-time-zone). Then you could use: `current_date` (based on sessiontimezone) instead of `sysdate` (based on OS time zone).

**Comment by Foxprodev** [comment]
@dmcghan Thank you, I will leave feedback here later.

**Comment by Foxprodev** [comment]
Code works until It gets thousand of coordinates. The problem is NJS-032.

**Comment by dmcghan** [comment]
@Foxprodev If you update your code with the latest version, I'll review it to see if I can spot the cause of the NJS-032.

**Comment by Foxprodev** [comment]
@dmcghan Thank you, I've already fixed this error - `async.eachSeries` works perfect for me.  Stop calling `callback(error)` in `aync.each` could be a good idea too.
