### ISSUE TITLE
Executing SQL script from node-oracledb

### ISSUE THREAD

**Issue by bmundt** [oracle/node-oracledb#552]
Is there a way to execute a sql script that exists either locally(preferably) or remotely on the Oracle Database, using this oracledb module. Basically I want to be able to do: "@myscript.sql;", or "START myscript.sql;" just like I can in sqlplus.

When I try to just put those commands in connection.execute() I get the following error:

ORA-00900: invalid SQL statement

**Comment by nmaynes** [comment]
The `connection.execute` function expects an argument of type string which is why you see the invalid SQL statement error. 

If you need to read a script, you could use the [fileSystem](https://nodejs.org/api/fs.html#fs_file_system) API provided by node to open the file and load it into a variable of type string. That would allow you to pass a SQL statement that exists in a file through the `connection.execute` function. I am not sure how that would handle script parameters eg. `set tab off, set trimspool off, set wrap off`
