### ISSUE TITLE
Installation - Cannot find module 'nan' issue in windows 

### ISSUE THREAD

**Issue by drtuts** [oracle/node-oracledb#583]
trying to install oracledb in windows machine, started facing issues. that Cannot find module 'nan', kindly please find the attached screenshot along with this. and help me to resolve this issue.

![oracledb](https://cloud.githubusercontent.com/assets/16743618/21679005/8818df70-d367-11e6-89ee-2a0890136e7c.png)

**Comment by bchr02** [comment]
I notice that you are using the global flag when installing oracledb. Do you get the same error without the global flag? 

To fix the issue, can you try doing a global install of nan and then try and install oracledb again?

npm install -g nan

**Comment by drtuts** [comment]
Thanks for your response bill, i tried both global & specific to the folder as well. I got the same error, I already installed 'nan' globally. Even though i am getting the same error.
Kindly please let me know is there any other way to resolve this issue.

**Comment by bchr02** [comment]
To rule out this being caused by a previous bug, make sure you have the latest LTS version of Node installed. Then:
* update npm to the latest version ```npm install npm -g```
* cd into your project folder
* ```npm uninstall nan -g```
* ```npm uninstall nan```
* ```set ORACLE_HOME=C:\instantclient```
* ```set OCI_LIB_DIR=%PATH_TO_ORACLE_HOME%\sdk\lib\msvc```
* ```set OCI_INC_DIR=%PATH_TO_ORACLE_HOME%\sdk\include```
* ```npm install node-oracledb```

*CHANGE THE ORACLE_HOME PATH IN THE ABOVE STEPS TO THE CORRECT PATH OF YOUR ORACLE FILES. Also these steps assume you have Python installed and available in your PATH environmental variable.


Alternatively, you could try my precompiled node-oracledb by following the steps [here](https://github.com/oracle/node-oracledb/issues/18)

**Comment by bchr02** [comment]
In case you are interested getting up and running quickly, I just published [oracledb-pb](https://www.npmjs.com/package/oracledb-pb) more information can be found here: https://github.com/bchr02/node-oracledb/tree/easy_pb

**Comment by cjbj** [comment]
@bchr02 thanks for looking at this.
