### ISSUE TITLE
rows outof resultSet

### ISSUE THREAD

**Issue by RavGup** [oracle/node-oracledb#589]
I have query that returns may be 500 rows or more.(not predicted)
When I am using ResultSet to get the rows, How would I collect all the rows from resultSet after iteration? 
I have this method

var fetchRowsFromRS = function (connection, resultSet, numRows)
{
  
  resultSet.getRows( // get numRows rows 
     numRows, 
     function (err, rows) 
     { 
       if (err) { 
         console.log(err); 
         doClose(connection, resultSet); // always close the result set 
       } else if (rows.length === 0) {    // no rows, or no more rows 
         doClose(connection, resultSet); // always close the result set 
       } else if (rows.length > 0) { 
         console.log("fetchRowsFromRS(): Got " + rows.length + " rows"); 
         
         fetchRowsFromRS(connection, resultSet, numRows); 
       } 
    });
}

How can I modify the above method so, I can get all the response rows togeather?

**Comment by sagiegurari** [comment]
Either put a really large value in the [max rows](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#propdbmaxrows) and don't even bother with resultsets if you keep everything in memory anyway

````js
var oracledb = require('oracledb');
oracledb.maxRows = 100;
````

Or use the [query](https://github.com/sagiegurari/simple-oracledb#Connection+query) function of simple-oracledb which returns all results (its actually using resultset internally) and you get an array of row objects returned.

````js
//read all rows and get an array of objects with all data
connection.query('SELECT department_id, department_name FROM departments WHERE manager_id < :id', [110], function onResults(error, results) {
  if (error) {
    //handle error...
  } else {
    //print the 4th row DEPARTMENT_ID column value
    console.log(results[3].DEPARTMENT_ID);
  }
});
````

**Comment by cjbj** [comment]
> Either put a really large value in the max rows and don't even bother with resultsets if you keep everything in memory anyway

This is a not a great idea because it will cause unnecessary memory allocation (unless maxRows is always very close to the number of rows being fetched - which is unlikely).  The bigger the difference between maxRows and the number of rows fetched, then the bigger the memory waste.

@RavGup just build up an array of results, appending each set of rows returned from getRows. Or use a library that does it for you, e.g. @sagiegurari's

**Comment by sagiegurari** [comment]
why would maxRows allocate more memory if actual query result rows count is less?

**Comment by cjbj** [comment]
@sagiegurari it preallocates mem so data from the DB can be fetched directly to it. (Or it did - I don't believe it's changed).

**Comment by sagiegurari** [comment]
wonder how if you don't know ahead of time the amount of columns or the size of data in each column per row.
but point well taken.

**Comment by cjbj** [comment]
@sagiegurari that column 'describe' info is (or can be) available early before the fetch.  There are various behaviors & subtleties about execute/describe/fetch/pre-fetch that OCI has, and we tried to exploit to fit with Node.

**Comment by calvinrajat** [comment]
I implemented the method  per my requirement : 


function fetchRowsFromRS(connection, resultSet, numRows, callback){
  var response =[];
  return resultSet.getRows(
    numRows,
    function (err, rows)
    {
      if (err) {
        dbConnector.closeResultSet(resultSet, connection);
      } else if (rows.length > 0) {
        response.push(rows);
        if (rows.length === numRows){
          fetchRowsFromRS(connection, resultSet, numRows,callback);
        } else {
          dbConnector.closeResultSet(resultSet, connection);
          logger.debug('Successfully retrieved rows from dBResponse ', response, metadata);
          callback(null,response);
        }
      } else {
        dbConnector.closeResultSet(resultSet, connection);
        logger.debug('Successfully retrieved rows from dBResponse ', response, metadata);
        callback(null,response);
      }
    });
}

as said by @cjbj  pushing the rows into the array, it suffices my purpose of getting the resultSet. 
But since it uses recursion , I m still stuck at the point that it will be faster if we have  bulk of data coming from database

**Comment by cjbj** [comment]
I'm not sure where you are heading with this. You have the choice of using `execute()` with or without ResultSets, or using `queryStream()`.  Then you can do various things to tune node-oracledb behavior, specially if queries are repeated or fetch small amounts of data.  Then there is JS tuning, network tuning, DB tuning, OS tuning, doing the processing in PL/SQL in the DB, writing in C, . . .

**Comment by ahummel25** [comment]
@cjbj @calvinrajat I'm having a similar issue where I'm calling a PL/SQL procedure which returns a ref cursor of data (data set could be huge).

I was under the impression I could use the `prefetchrows` in an `execute` call to limit the results. But this still returns all the results from my procedure. I recursively call a function basically identical to `fetchRowsFromRS` up above, but I continuously get a memory leak error due to the volume of data. 

`const result = await conn.execute('call my_pkg.my_proc(:my_ref_cursor)', my_bind_var, {
          prefetchRows: 1000
        })`

How can we limit the number of rows returned? Similar to pagination type functionality...

**Comment by cjbj** [comment]
@ahummel25 `prefetchRows` was an internal buffer size - it didn't affect the number of rows ultimately returned.  Also it was replace in node-oracledb 2.0, see [this](https://blogs.oracle.com/opal/node-oracledb-v2-query-methods-and-fetch-tuning).

Check the REF CURSOR examples [here](https://github.com/oracle/node-oracledb/blob/master/examples/refcursor.js)  and [here](https://github.com/oracle/node-oracledb/blob/master/examples/refcursortoquerystream.js) and let us know if you have more questions.

If you need to truncate a query set then it's better to do that in the query so unused rows don't get processed by the DB, and then returned to node-oracledb.  See [here](https://oracle.github.io/node-oracledb/doc/api.html#pagingdata).

**Comment by ahummel25** [comment]
Was just reading that last link you provided. I think `offset` and `maxnumrows` is probably the way to go. Only thing you have to account for is cutting data off (ex. you have a lines table with 11 rows, but your `maxnumrows` is set to fetch only 10, you lose that 11th row in your results).
