### ISSUE TITLE
Multiple request failure and getting [Error: ORA-12516: TNS:listener could not find available handler with matching protocol stack 

### ISSUE THREAD

**Issue by calvinrajat** [oracle/node-oracledb#605]
While sending multiple request in apache jmeter to test for 100 api requests, I am getting some failed responses and the error corresponding to these failed request is :   

[Error: ORA-12516: TNS:listener could not find available handler with matching protocol stack 

After failing for some requests, the subsequent request are working fine.

My db configuration is :

  "poolMax":100,
  "poolMin":2,
  "poolIncrement":5,
  "poolTimeout":4,
  "poolAlias":"pool1"

Can you please tell me the reason for the same as the maximum pool size is also **not** reached ?

**Comment by cjbj** [comment]
Errors
```
  ORA-12516: TNS:listener could not find available handler with matching protocol stack
```
or
```
  ORA-12520: TNS:listener could not find available handler for requested type of server
```
typically occur if the DB server's `processes` setting isn't large enough. Bump this up.  If you're unsure how, there are command-line steps on p 318 of the free PHP & Oracle book http://www.oracle.com/technetwork/topics/php/underground-php-oracle-manual-098250.html

**Comment by calvinrajat** [comment]
Thanx  @cjbj

**Comment by mvorisek** [comment]
@cjbj Hi, we are hitting the ORA-12516 error since Oracle free v23.4 too.

The error is reproducible using oci8 and pdo_oci php drivers/clients. To reproduce it, it is enough to keep reconnecting in a loop. About in 1k-10k reconnects the ORA-12516 error is returned from the server.

I wonder if this issue is known and to be fixed. By one our project's developer I was inforced that is due Oracle listener not releasing the connections immediately, but it is insane that with only a few connections (<5 in parallel) the default limit of 200 sessions/processes is exhausted. It seems this should be fixed in Oracle database/listener.
