### ISSUE TITLE
Insert data with Oracle functions

### ISSUE THREAD

**Issue by DmsChrisPena** [oracle/node-oracledb#617]
So right now it appears that anytime I bind values to my insert command it will always read it as a string. Where as if I put it in sql string format it will execute as an Oracle function as it should.

Example:

```
conn.execute(
 "INSERT INTO table (:id, :name, :createdAt)",
{
   id: 1,
  name: "Chris",
  createdAt: "TO_DATE('2017-02-12T11:41:57-06:00')"
}
).then...
```

The result is createdAt saving as the exact string, 'TO_DATE('2017-02-12T11:41:57-06:00')', instead of executing the function.

**Comment by cjbj** [comment]
Bind variables are always treated as data.  From the [manual](https://github.com/oracle/node-oracledb/blob/v1.12.2/doc/api.md#bind):
> Inserted data that is bound is passed to the database separately from the statement text. It can never be executed. 

This is why the whole string including the text `TO_DATE` is inserted.  This an 'Oracle' thing, not specific to node-oracledb.   This will work:

```
 "INSERT INTO table (:id, :name, to_date(:createdAt))" 
```
and bind
```
createdAt: '2017-02-12T11:41:57-06:00'
```

Or check out inserting a JS date object in [examples/date.js](https://github.com/oracle/node-oracledb/blob/v1.12.2/examples/date.js).

Since you're working with dates, review https://github.com/oracle/node-oracledb/blob/v1.12.2/doc/api.md#datehandling
