### ISSUE TITLE
Can I use template literals in my queries?

### ISSUE THREAD

**Issue by sibelius** [oracle/node-oracledb#630]
I would like to use template literals in my queries - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

something like this:

```jsx
conn.execute(`select id, name from users where id = '10'`)
```

is it possible already?

**Comment by dmcghan** [comment]
@sibelius You can use template literals as long as you're using a version of Node.js that supports them. They can be convenient because new lines are easier to work with. However, they must be used with caution.

This would be bad and open you up to SQL injections and performance issues:
```javascript
var id = valueObtainedFromEndUser;

conn.execute(`select id, name from users where id = {id}`);
```

Using bind variables keeps you safe and performant:

```javascript
var id = valueObtainedFromEndUser;

conn.execute(`select id, name from users where id = :id`, {id: id});
```

**Comment by sibelius** [comment]
tks for the answer
