### ISSUE TITLE
request for docker image with node-oracledb and instant client

### ISSUE THREAD

**Issue by mrchulho** [oracle/node-oracledb#640]
An official docker image with node-oracledb and the instant client would be helpful. We can use it as a base image, and add custom node apps and deploy readily. We could mount a volume of oracle wallet as external credentials.

Thanks,

**Comment by sagiegurari** [comment]
https://github.com/CollinEstes/docker-node-oracle
This is what I use for testing

**Comment by gvenzl** [comment]
Thanks @cjbj. While a Docker image with instant client already installed may be useful, I struggle to see how an image for the Node.js driver makes much sense. Usually applications/app developers want to be very specific about which version of the driver the app supports rather than just using the latest and greatest. And even if not, the driver can be easily installed via npm, whether that's in a Dockerfile or inside a setup script. Or am I missing something here?

**Comment by sibelius** [comment]
@mrchulho I'm using this https://github.com/CollinEstes/docker-node-oracle

can we close this issue?

**Comment by mrchulho** [comment]
Instant Client is available for Docker
A Docker image with the Basic, SDK and SQL*Plus packages is available on the [Docker Store](https://store.docker.com/images/oracle-instant-client?tab=description) or from the [Oracle Container Registry](https://container-registry.oracle.com/). Docker build files are available on [GitHub](https://github.com/oracle/docker-images/tree/master/OracleInstantClient).

https://www.oracle.com/database/technologies/instant-client.html

**Comment by cjbj** [comment]
For more discussion, see the node-oracledb installation documentation: https://oracle.github.io/node-oracledb/INSTALL.html#docker

**Comment by cjbj** [comment]
For future readers, also see https://blogs.oracle.com/opal/docker-for-oracle-database-applications-in-nodejs-and-python-part-1 and https://learncodeshare.net/2019/08/27/howto-connect-your-nodejs-app-in-docker-to-your-oracle-database/
