### ISSUE TITLE
Is it possible to add a method like connection.isValid()?

### ISSUE THREAD

**Issue by JonathanFu** [oracle/node-oracledb#652]
### Is it possible to add a method like `connection.isValid()` similar to the JDBC  `java.sql.Connection.isValid()`?

There are some cases we want to check the connection if it is still valid.

E.g. If you try to close a connection twice, or use a closed connection. You will get an error `Error: NJS-003: invalid connection`.

Below is a possible use case for releasing connection twice.

```javascript
var oracledb = require('oracledb');
oracledb.getConnection(dbConfig).then(function (conn) {

  conn.execute(sql, bindParams, options).then(function (result) {

    doRelease(conn); // Release connection
    
    // Other logics  // <= Error may happen here
   
    // Return callback
    callback(null, result);  // <= Error may happen here

  }).catch(function (err) {
    doRelease(conn); // Always try to release connection
    callback(err);
  });

}).catch(function (err) {
  callback(err);
});

function doRelease(conn) {
  if (conn.isValid()) { // Want to check it before calling release method, otherwise it will throw "Error: NJS-003: invalid connection"
    conn.release().catch(function (err) {
      if (err) console.error(err);
    });
  }
}
```

Thanks

**Comment by cjbj** [comment]
Or release() could be a no-op if the connection is already closed?

**Comment by xpiwo** [comment]
```
var db_con;

oracledb.getConnection(function(con){
    db_con = con;
});

...
...

async(function(){
    release(db_con);
    db_con = undefined; // early release
});

...
...

on error/cleanup(function(){
    release(db_con);
});


var release = function(con){
    if(typeof con === 'undefined')
        return;
    ...
};
```

**Comment by dmcghan** [comment]
@cjbj Race conditions will make `isValid` less than perfect. 

In the example from @JonathanFu, the first call to `doRelease` will check `isValid` synchronously and get `true` back causing it to call the async `conn.release` method. Because it's async, when the connection is marked as invalid can vary. 

So, depending on when the error occurs, the second call to `doRelease` may still see the connection as valid (even though a call to close/release was already made). If that happens then the second call will get `NJS-003: invalid connection`.

Even a no-op might not be perfect for the same reasons. We could catch the `NJS-003: invalid connection` within the call to `close`/`release` and mask it. Maybe there's a better option from the C layer? Is it safe to assume a connection close call will work and mark the connection closed ahead of time?

Whatever we decide we should probably look at doing the same for other classes where it makes sense.

**Comment by JonathanFu** [comment]
@cjbj, @dmcghan 
Thanks for explanation.

From @dmcghan: ```Is it safe to assume a connection close call will work and mark the connection closed ahead of time?```
I think we cannot 100% guarantee the connection status since (releasing connection) error may happen inside C layer.
Look at ```connection.release()``` in ```oracledb``` module below:
```javascript
// This release function is used to override the release method of the Connection
// class, which is defined in the C layer.
function release(releaseCb) {
  var self = this;

  nodbUtil.assert(arguments.length === 1, 'NJS-009');
  nodbUtil.assert(typeof releaseCb === 'function', 'NJS-006', 1);

  self._release(function(err) {
    if (!err) { // <= If error happens inside C layer the connection may be not released??
      self.emit('_after_close');
    }

    releaseCb(err);
  });
}
```

BTW, if checking C layer connection status (```isValid()```) is very efficient, can we implement the node method ```isValid()``` by calling C layer method```isValid()``` **synchronously**?

Otherwise can we implement ```isValid()``` by calling C layer method ```isValid()``` **asynchronously** shown as below?
Callback:
```isValid(function(Error error){});```

Promise:
```promise = isValid();```
 
Thanks

**Comment by dmcghan** [comment]
@JonathanFu The problem is that checking the current status will not tell you if you have already invoked the `close` method, which is async. So if you check the current status, then invoke close, you might still get the error.

When these errors occur, especially if you try to use a method after closing a connection, then it's usually an indication there's something wrong with the way the application was written.

Here's an example of how your app could be rewritten using promises that only calls `close` once. I put the logic in a function so that I could test it:
```javascript
const oracledb = require('oracledb');
const config = require('./dbConfig.js');
 
function processData(callback) {
  let conn;
 
  oracledb.getConnection(config)
    .then(function(c) {
      conn = c;
 
      return conn.execute('select * from employees');
    })
    .then(function(result) {   
 
      // process result
 
      callback(null, result.rows);
    })
    .catch(function(err) { // Catches errors in getConnection and result processing
      callback(err);
    })
    .then(function() {
      if (conn) { // the conn assignment worked, must release
        return conn.release();
      }
    })
    .catch(function(err) {
      console.log(err); // want to know, but callback already invoked
    });
}
 
processData(function(err, data) {
  if (err) {
    console.log('done with error', err);
  }
 
  if (data) {
    console.log('done with success', data.length);
  }
});
```

With Node.js 7.6+ supporting the goodness of async/await, the traditional try/catch/finally can be used again:
```javascript
const oracledb = require('oracledb');
const config = require('./dbConfig.js');

async function processData(callback) {
  let conn;

  try {
    conn = await oracledb.getConnection(config);
    let result = await conn.execute('select * from employees');

    // process result.rows

    callback(null, result.rows); 
  } catch (err) { // Catches errors in getConnection and result processing
    callback(err); 
  } finally {
    if (conn) { // the conn assignment worked, must release
      try {
        await conn.release();
      } catch (e) {
        console.log(e); // want to know, but callback already invoked
      }
    }
  }
}

processData(function(err, data) {
  if (err) {
    console.log('done with error', err);
  }

  if (data) {
    console.log('done with success', data.length);
  }
});
```

**Comment by JonathanFu** [comment]
@dmcghan
Thanks for your answer. Yes, your solution is better, I will use it.

Actually my initial thought is that if it is easy to implement a `isValid()` since I can just ignore the error in my application.
But it seems a bit complicated to implement and it is not a must-have function, I am going to close this now.

Thanks for your suggestion.
