### ISSUE TITLE
Parameter metadata support for Prepared statement

### ISSUE THREAD

**Issue by sonia1588** [oracle/node-oracledb#679]
Is there support for Parameter metadata for Prepared statement?
For e.g.   Java driver has provision getParameterMetadata() function for prepared statements https://docs.oracle.com/javase/7/docs/api/java/sql/PreparedStatement.html#getParameterMetaData() 

Is it supported on node-oracledb?

We found metadata on Resusltset support available on oracledb node. we are looking for parameter metadata prior to query execute.

**Comment by dmcghan** [comment]
@sonia1588 I'm not sure I understand... The [metadata that the driver provides](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#-42541-metadata) is related to the columns in a query, not parameters passed in (bind variables). 

I've had a use case for getting this metadata prior to executing a query. Perhaps we're really talking about the same thing? I ended up [having to implement it manually](https://github.com/dmcghan/query-wrap/blob/master/src/query-cache.js) via dbms_sql.

**Comment by cjbj** [comment]
@sonia1588 the only way to get metadata to Oracle DB clients (like node-oracledb) is to invoke something that interrogates the DB.  I.e. there is going to be some overhead.  If you choose to query base tables (e.g. `user_tab_columns`) or call `dbms_metadata.get_ddl` you will get information about objects. But you won't get info about query column functions, e.g. `to_date()`.

Depending what level of information you need, an alternative is to append a `WHERE 0=1` clause to the query and call oracledb.execute().  This will be the fastest - but may not have all the info you want.

node-oracledb doesn't have prepared statements because it uses [statement caching](https://github.com/oracle/node-oracledb/blob/v1.13.1/doc/api.md#stmtcache).

**Comment by dmcghan** [comment]
Another option is to use `dbms_sql.parse` and `dbms_sql.describe_columns3`. That should work with query column functions.

**Comment by cjbj** [comment]
Closing - no feedback.
