### ISSUE TITLE
numerical precision problems  for special value

### ISSUE THREAD

**Issue by freeman983** [oracle/node-oracledb#68]
The same SQL I found using PLSQL and node-oracledb will have different results,But only a special value will be different，like 226.7 

 sql:

	SELECT
	    b.tid, b.TOTAL_FEE,b.TOTAL_CASH
	from B_TRADE b  where tid in('T201503301318852','T201503041418667')

plsql:

TID	               ｜             TOTAL_FEE	 ｜      TOTAL_CASH
T201503041418667｜	269.2000	  ｜           793.8000
T201503301318852｜	792.3000	    ｜         226.7000

node-oracledb：
TID	|TOTAL_FEE|	TOTAL_CASH	
T201503041418667|	269.2	|793.8000000000001	|
T201503301318852|	792.3000000000001|	226.70000000000002|	

desc:
TOTAL_FEE NUMBER(20,4),
TOTAL_CASH  NUMBER(20,4)

query options：
  {outFormat: Oracle.OBJECT, maxRows: 10000}

**Comment by cjbj** [comment]
@freeman983 This is not unexpected, since numbers are represented differently in Oracle DB and Node.js.  There is ongoing discussion in https://github.com/oracle/node-oracledb/issues/20 about mapping database types to Node.js types.  When this feature is implemented it will help with some of these issues.

In general, making use of PL/SQL procedures for number calculations might save some headaches. This  is specially true for financial calculations.
