### ISSUE TITLE
Intermittent ORA-12154 errors

### ISSUE THREAD

**Issue by larryaubstore** [oracle/node-oracledb#698]
Hi, 

I use knex over node-oracledb. This errors happens randomly and this errors is not specific to one route. When this error occurs, I have to restart the docker container and after everything is working normally. 

I use version 1.13.1 + instantclient-sdk 12.1.0.2.0 (64). 

Is there a way to track the problem in the c/c++ node oracle db driver ? I think an errors occurs sometimes in the c/c++ part of the code ...

**Comment by larryaubstore** [comment]
It seems related to https://github.com/oracle/node-oracledb/issues/300. I think the pool does not manage well network disconnection.

**Comment by cjbj** [comment]
@larryaubstore why do you think it is related to #300?   The error ORA-12154 seems unrelated to pooling behavior.

What is your app doing?  Do you have 'idle' time?  Is something in your network killing idle network connections?  Do all connections in the container become unusable - are there any other errors?

[The pool is designed with certain behaviors e.g. for performance and scalability.  These include not doing unnecessary 'round trips' to the database.   In general I'd recommend using Instant Client 12.2, since this improves some [pool behaviors](https://github.com/oracle/node-oracledb/blob/v1.13.1/doc/api.md#propdbpoolpinginterval).  I don't think any of the changes will solve your issue, but will improve the network drop-out case documented.]

**Comment by larryaubstore** [comment]
I think it's related because the failing scenarios are pretty similars to my use case:

> Our failing scenario:

> Initialize connection pool with poolMin=0, poolMax=5, poolTimeout=0, which means oracledb driver will never terminate already initialized connections, and keep them in pool infinitely.
Execute any query using connection from pool, release it. Connection is initialized from now, but not busy.

> After some time (usually next working day) make attempt to execute next query. Node application is still running.

> Node oracledb driver attempts to utilize connection from pool and gains ORA-03135 error, since connection is already not valid due to some network-related issues.

I applied the recommanded fix (poolTimeout to 60 seconds) and I still having the same issue. 

My app is a node js API with an Oracle database.  The API has 'idle' time, idle times can last more than 24 hours. Our network is a bit instable, I notice frequent disconnections.

**Comment by larryaubstore** [comment]
@cjbj 

> The ping (either the time-based poolPingInterval, or the new, underlying OCI 12.2 check) can only help if the app has closed the connection (i.e. released it back to the pool) when it not in use. Are you doing this?

No, I'm not releasing connection.

> Where does the ORA-12154 error fit with the ORA-03135 error? ORA-12154 sounds like a DNS issue. 

IMO, the pool is responsible to give connections to the client. If the pool is unable to give a connection because its inner state is invalid, it is a pool problem. When I restart the process, everything comes back to normal.  Maybe it's related to a DNS issue ... However, the pool should be able to go back on its feets after a DNS error. 

> What kind of connect strings are you using?

I'm using [//]host_name[:port][/service_name][:server_type][/instance_name]. I have a service name, host name, port.

**Comment by cjbj** [comment]
> No, I'm not releasing connection.

Game over in some senses.  If the network drops out, your app will get an error when it tries to use the connection.  The app will need to release the connection, get a new one, and do whatever work it was intending to do.

I'm not quite sure of your scenario yet, since I am getting piecemeal information.  Perhaps you can give a full description of what connections are open, what errors are seen, what the code tries to do to close & reopen connections etc.

> If the pool is unable to give a connection because its inner state is invalid, it is a pool problem.

The OCI session pool is designed to be efficient in the common case of a relatively stable network environment.  It doesn't make unnecessary round-trips, since these will impact scalability.  This includes not checking by default if a session is usable: your app already needs to do error checking after execute() in case the network drops after getConnection() returns.

Applications can control whether they always 'ping' to check the connection, and how they handle errors.  There is also Oracle's FAN feature which is useful for RAC or DG environments.

Drivers like node-oracledb bias towards usability with explicit features for time-based connection pinging, and with the automatic server status checks https://github.com/oracle/node-oracledb/blob/v1.13.1/src/dpi/src/dpiConnImpl.cpp#L557-L565 and https://github.com/oracle/node-oracledb/blob/v1.13.1/src/dpi/src/dpiConnImpl.cpp#L861

I don't have access to the code underlying OCI_ATTR_SERVER_STATUS to check but I believe that the 12.2 client treats 3135 as a case that the connection should be dropped.  (And 3135 is explicitly in ODPI-C https://github.com/oracle/odpi/blob/master/src/dpiError.c#L105 which will be used by the future node-oracledb v2)

If 3135 isn't being handled in your client version, and you are ending up with unusable sessions, we can add a patch.

As a test for 3135 behavior, add `case 3135:` into the `switch()` statement at https://github.com/oracle/node-oracledb/blob/v1.13.1/src/dpi/src/dpiConnImpl.cpp#L557-L565

Let us know what you see.

The OCI session pool has also been enhanced in the Oracle 12.2 client, as noted in the node-oracledb doc.  I'd recommend you upgrade.

> I'm using [//]host_name[:port][/service_name][:server_type][/instance_name]. I have a service name, host name, port.

If you are using a hostname, then obviously you could be impacted by DNS issues.  If your IP address are static, you could hardcode the IP address.

**Comment by larryaubstore** [comment]
@cjbj Sorry I gave the wrong information. I released connection, knex with its pool management (abstraction layer over node-oracledb pool) do it for me :-)

Thank you for all the information. I like your ideas to hardcode IP address for the DNS issues. To begin, I will try this solution. I will come back to you with results.

**Comment by larryaubstore** [comment]
Unfortunately, the addresses were already harcoded. I used the _extra_hosts_ option in _Docker_ to hardcode ip addresses. 

For the moment, I catch ORA-12154 errors and force a restart of the Docker container. I don't see other solutions for now :-(

**Comment by cjbj** [comment]
@larryaubstore Can you (i) tell me the complete behavior you are seeing (ii) use Instant Client 12.2 (iii) try the patch I suggested.

**Comment by larryaubstore** [comment]
@cjbj 
Of course, I will do the test you proposed. I will come back to you with the results.

**Comment by larryaubstore** [comment]
@cjbj 

I did the patch: https://github.com/larryaubstore/node-oracledb/commit/bec1ed19fc2e0bcbfecd80b39c1ac305a6aac549

 It is deployed. I will monitor to see if the problem is fixed.

**Comment by cjbj** [comment]
@larryaubstore let me know which client you use.

**Comment by larryaubstore** [comment]
@cjbj The problem was in 'instantclient-sdk 12.1.0.2.0'. For the test with the patch, I updated to 12.2.0.1.0 version.

**Comment by larryaubstore** [comment]
@cjbj 

Great ! It looks like the problem is fixed !

However, I don't know if the problem has been fixed with the new instant-client version or with the patch.

**Comment by cjbj** [comment]
@larryaubstore well, you can always back out one or the other.

Anyway, v2 is coming, which has the patch in the ODPI-C layer it uses.

The v2.0.13-dev release announcement is at https://blogs.oracle.com/opal/node-oracledb-2013-development-is-now-on-github

I'll close this now.  Keep in touch with what you find.

**Comment by sdesilvagb** [comment]
@cjbj I don't want to reopen this issue but I weirdly start getting this 3135 error when I pointed my code from staging to prod db. Our DBAs have set SQLNET.expire_time to 60 seconds. Here is my pool configuration 
``` 
poolMax: 24,
queueTimeout: 0, // never terminate queued connection request,
stmtCacheSize: 10000
```
I'm using oracledb v2.1.2 and instant-client v12.2.0.1.0
