### ISSUE TITLE
oracledb@1.13.1 install: `node-gyp rebuild`

### ISSUE THREAD

**Issue by felipon1810** [oracle/node-oracledb#721]
Tengo el siguiente problema en un Windows 10 64bits:

Soy nuevo en este tema y no he podido resolverlo

[2017-06-22T19_00_19_682Z-debug.log.txt](https://github.com/oracle/node-oracledb/files/1095901/2017-06-22T19_00_19_682Z-debug.log.txt)

**Comment by sibelius** [comment]
follow this https://github.com/oracle/node-oracledb/blob/master/INSTALL.md

**Comment by cjbj** [comment]
Closing - no update from user

**Comment by josecarlosbarros** [comment]
Still not working same issue ~here. 
come on guys ! there are no other way to solve issues on those stuff

**Comment by josecarlosbarros** [comment]
The tutorial is just too old there are no SDK folder on instantclient

**Comment by dmcghan** [comment]
@josecarlosbarros This isn't a tutorial, it's an issue. 

Are you referring to the [installation documentation](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md)? 

If so, the part on the [Oracle Instant Client Zips](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#73-install-the-free-oracle-instant-client-zips) reads:

> download the free Instant Client Basic and SDK ZIP files

Did you download both?

**Comment by cjbj** [comment]
@josecarlosbarros since it's a C/C++ add-on, it needs to be built with a compiler.  That's just the way it is, and will be.

As for pre-built binaries, @dmcghan did some refactoring re-work recently on the idea I mentioned in https://github.com/oracle/node-oracledb/issues/18#issuecomment-322675513 and we have some progress.  More to come.
