### ISSUE TITLE
NJS-050: data must be shorter than 65535

### ISSUE THREAD

**Issue by asadbsse** [oracle/node-oracledb#768]
I am trying to save picture in BLOB and getting error **NJS-050: data must be shorter than 65535**
Its working fine with oracledb **version oracledb@1.11.0** but it throws error with  **oracledb@1.13.1**

Please give me the solution

**Comment by cjbj** [comment]
Review the LOB [documentation](https://github.com/oracle/node-oracledb/blob/v1.13.1/doc/api.md#lobhandling) and [examples](https://github.com/oracle/node-oracledb/tree/v1.13.1/examples).  If you need more help, please fill in the [issue template](https://github.com/oracle/node-oracledb/blob/v1.13.1/.github/issue_template.md) because we have no idea what you are doing.
