### ISSUE TITLE
Question/Doubt: Is SYS.ODCIVARCHAR2LIST() supported by node-oracledb ?

### ISSUE THREAD

**Issue by danilohgds** [oracle/node-oracledb#798]
Hi Guys,

I am wondering if the system object for varchar2 tables from Oracle11 and forward is supported by the node oracle db project or not. I could not find any documentation about it nor usage examples.

**Comment by cjbj** [comment]
Can you define what 'support' means to you so we know how you like to use it?

https://github.com/oracle/node-oracledb/blob/node-oracledb-v1/doc/api.md#plsqlindexbybinds says "Note PL/SQL's VARRAY and nested table collection types cannot be bound."

Also see https://github.com/oracle/node-oracledb/issues/147

**Comment by danilohgds** [comment]
Hi Christopher, sorry if I was too brief in my question.

In my project I was able to use collections of VARCHAR2 with bind variables.
```
 ARR_NUMBER: { type: oracledb.NUMBER, dir: oracledb.BIND_IN, val: args.map(args=> args.number || null) },  
 ARR_NAME: { type: oracledb.STRING, dir: oracledb.BIND_IN, val: args.map(args=> args.name|| null) },  
```
That being said, this would essentially handle, most, if not all cases where you need arrays. I'm confused whether the VARRAY mentioned in the documentation is the one declaration below, because it works!

  TYPE test_collection_type is table of VARCHAR2(60);  

The only problem is, in my case, I cannot access rows from a nested table all at once (using a join or cast as table), because I'm on 11g.

That being said, I wondered whether there is or there will be support in the future for custom types such as user-defined ones, or previously made available by oracle like SYS.ODCINUMBERLIST.

I hope this clarifies my question and thanks for taking the time to answer me out man :)

**Comment by cjbj** [comment]
> TYPE test_collection_type is table of VARCHAR2(60);

They are [Associative Arrays](https://docs.oracle.com/database/122/LNPLS/plsql-collections-and-records.htm#LNPLS99969).

We're using #147 as the placeholder tracking the request to support other UDT binds.  The ODPI layer used in v2 and in cx_Oracle (for Python) allows [cx_Oracle to bind UDTs](https://github.com/oracle/python-cx_Oracle/tree/master/samples), so theoretically adding support in node-oracledb is a matter of priorities and resources.  This is  a goal rather than a promise.  Note that layers beneath node-oracledb & ODPI have a restriction or two, e.g. on binding PL/SQL index-by varchar2.

I'll close this and we can follow up in #147, if you like.
