### ISSUE TITLE
Using oracledb.maxRows - How detect that the query result count exceeds maxRows?

### ISSUE THREAD

**Issue by aprixon01112017** [oracle/node-oracledb#809]
Let the query return 101 rows, let oracledb.maxRows be 100 -> The results contain 100 rows. How do I detect that the query results were cropped?

**Comment by danilohgds** [comment]
Oracle itself does not have such feature. If you are uncertain of the amouny of rows returned, consider using a resultSet object instead.

**Comment by aprixon01112017** [comment]
Thanks. I want to get JSON objects and afik I cannot get those via the ResultSet route.
oracledb should be able to know that it just cropped the resulting row set. Or does it limit the query itself?

**Comment by dmcghan** [comment]
In the latest release, v2.0.15 (released today), maxRows [now defaults to 0](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#-329-oracledbmaxrows ) which means unlimited.

Yay!!! 🎉🎉🎉 

> I want to get JSON objects and afik I cannot get those via the ResultSet route.

I'm not sure what you mean here. Standard execute, ResultSet, and QueryStream all return native JavaScript objects. You can specify the [outFormat](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#oracledbconstantsoutformat) as `oracledb.OBJECT` to get objects (often easier to work with) over the default arrays (more performant due to less redundancy).

Once you have the JavaScript you can convert to JSON with `JSON.stringify()`.

**Comment by dmcghan** [comment]
Oh, by the way, you'll want to read this post from @cjbj:
https://blogs.oracle.com/opal/node-oracledb-v2-query-methods-and-fetch-tuning

**Comment by cjbj** [comment]
I'll close this.  I believe it has been answered: use v2.
