### ISSUE TITLE
npm i nodeoracledb should take care of everything

### ISSUE THREAD

**Issue by VenPot** [oracle/node-oracledb#815]
Right now we have plethora of prerequisites to use this and it is becoming a deterrent for new programmers in node to seriously consider using node -oracle db. Is it possible to make changes so that people can just install node-oracledb and are good to go and not worry about (ptyhon,Vs studio etc)

Please excuse if you consider this as wishful thinking :)

**Comment by danilohgds** [comment]
Hi,

Read up on the new install.md from 2.0 versions forward. Binaries for windows and linux has been added so compiling is no longer required, unless your environment is not one out of those two.

And yeah, kind of wishful thinking if you ask me, any developer should be able to follow up the installation steps :)

**Comment by dmcghan** [comment]
@VenPot As of the latest release, v2.0.15, the list of prerequisites has gone down. We now ship pre-built binaries for the most popular platforms and versions of Node.js. Granted, you still have to put the Oracle Client libraries in place, but python and VS Studio (gcc) shouldn't be needed unless you can't use the prebuilt binaries for some reason.

Have you done a recent install? If so, which version of node-oracledb?

**Comment by cjbj** [comment]
The Oracle client libraries and network layer do all the heavy lifting in terms of data transfer management, auto-tuning, security etc, so I don't see them disappearing. 

@VenPot I appreciate you taking the time to comment, and your request has been noted.  I'll close this issue since it has made its point.  

Check out the [pre-built binaries](https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#quickstart) for Windows, macOS and Linux as mentioned by @danilohgds and @dmcghan

**Comment by VenPot** [comment]
Thanks all. I haven't used the latest version yet but will give that a try.
Appreciate everyone's time in replying to my query.
