### ISSUE TITLE
Closing connection pool in nodejs express

### ISSUE THREAD

**Issue by rubtk** [oracle/node-oracledb#843]
Since nodejs express doesn't allow to catch event, when session would be expired, i don't know where to call pool.close method. I want create connection pool per user in POST /session route, and destroy it using poolTimeout property. Would this a good idea? I see one alternative: not using connection pools and connect database with each user request, but this is not good due to security (i would need to keep password in session). What is the best practice?

**Comment by dmcghan** [comment]
@rubtk Let's take a step back. Please explain to us what type of application you're trying to build.

I see a reference to POST. Are you creating a REST API?

**Comment by dmcghan** [comment]
Diving a little deeper... Why do you want different connection pools for each user in the POST /session route? How does the mapping between app end users and database users work?

**Comment by rubtk** [comment]
Yes. I am building REST Api for simple web service: Backend would be NodeJS + Express, frontend would be ExtJS (I have already have front end, would be just adapt it for my REST API). The idea was made there authorization using Oracle DB, because there would not be much users (about 10-20 users maximum).

**Comment by dmcghan** [comment]
Ah, I see... I think your best bet would be to create a connection pool using a single database user for all of your regular routes. For the /session route, you're probably best off just trying to make a one-off connection with the user provided username/password.

You'll also need to use the one-off approach for password resets.

If you're not tied to this approach, you might have a look at this post with shows how to store users in a table: https://jsao.io/2015/06/authentication-with-node-js-jwts-and-oracle-database/

**Comment by rubtk** [comment]
Okay! By the way, we can solve a problem by using alternative node js express session backend, for example redis backend (which i dont want to do, coz i dont need redis for other purposes) or this
https://github.com/roccomuso/memorystore
so i think we can close issue, thanks for attention.

**Comment by cjbj** [comment]
@rubtk since the web is stateless, something in your app needs to pass a token with HTTP responses/requests to indicate that a web user is authenticated.  This is out of scope of node-oracledb.

Regarding DB authentication you may want to look at using [clientId](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#propconnclientid). See  [End-to-end Tracing, Mid-tier Authentication, and Auditing](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#endtoend).  

Also keep an eye on #796

Since you indicated this issue can be closed, I will do so.
