### ISSUE TITLE
Prebuilt binaries for Node 10

### ISSUE THREAD

**Issue by igor-savin-ht** [oracle/node-oracledb#901]
When trying to download prebuilt oracle driver for Node 10, following error is thrown:

```
oracledb ERR! NJS-054: Binary build/Release/oracledb.node was not installed.
oracledb ERR! Pre-built binary packages are not available for this version of Node.js (NODE_MODULE_VERSION="64")
oracledb ERR! Failed to install binary package oracledb-v2.2.0-node-v64-linux-x64.gz
oracledb ERR! Error: HTTPS request for https://github.com/oracle/node-oracledb/releases/download/v2.2.0/oracledb-v2.2.0-node-v64-linux-x64.gz failed with code 404
```

**Comment by cjbj** [comment]
That's not an error.  It is expected: Node.js 10 came out after the latest node-oracledb.   

Currently the test suite isn't running cleanly with Node.js 10; it needs some triage to check what's going on.  Try building and letting us know how it goes for you.  Thanks!

**Comment by igor-savin-ht** [comment]
@cjbj Not saying that this is an error, but it's definitely a gap. Wouldn't it make sense to keep the issue open with this explanation from your side in it? That would prevent people having same issue from having to raise the question over and over again, and it could also be used to track the effort to make driver build cleanly with  Node.js 10.

**Comment by cjbj** [comment]
Now where's the fun in that?!

**Comment by igor-savin-ht** [comment]
:D

**Comment by cjbj** [comment]
By popular demand..

**Comment by DanielRuf** [comment]
> Currently the test suite isn't running cleanly with Node.js 10

Are there some logs from CI / the tests with the errors / issues caused by Node.js 10 so we can help here?

**Comment by cjbj** [comment]
@DanielRuf I appreciate the eagerness.  I'm not seeing any particular blockers at the moment - it's now a matter of time & timing.  I'm about to head to [Oracle Code Shenzhen](https://developer.oracle.com/code/shenzhen-may-2018) - half the team will be there too.  At the end of the week we'll review the Node 10 status and let you know the plan.  Until then, happy compiling!   

A related question is whether to drop Node 4 immediately in the next node-oracledb release.

**Comment by sosoba** [comment]
>  Until then, happy compiling!
But why 404 does not lead to compiling?

**Comment by DanielRuf** [comment]
> But why 404 does not lead to compiling

Not sure what we need for this. It also depends on the package metadata.

**Comment by sosoba** [comment]
Dziękuję za wiadomość. Do 10.05.2018 będę przebywał na urlopie. W sprawach nie cierpiących zwłoki proszę o kontakt z Markiem Michalskim tel. 32-757-4351, email: marek.michalski@coig.pl.
  
  
  
  Sławomir Osoba
Lider Zespołu Z07

tel. (+48) 32 757 4192
tel. kom. (+48) 609 793 920
slawomir.osoba@coig.pl

 	 		 				 COIG S.A. | ul. Mikołowska 100, 40-065 Katowice | coig@coig.pl | www.coig.pl	  		 
  			Sąd Rejonowy Katowice-Wschód w Katowicach
			VIII Wydział Gospodarczy Krajowego Rejestru Sądowego KRS 0000092497,
			Kapitał zakładowy w kwocie: 5.400.000 zł, w całości wniesiony. NIP: 634-013-4205	  		

Dokument ten zawiera informacje poufne, które mogą być również objęte tajemnicą służbową. Jest on przeznaczony do wyłącznego użytku adresata.
Jeśli nie są Państwo jego adresatem, to wszelkie rozpowszechnianie, dystrybucja, reprodukcja, kopiowanie, publikacja lub wykorzystanie tego dokumentu lub informacji jest zabronione. Jeśli otrzymali Państwo tą wiadomość przez pomyłkę, prosimy o bezzwłoczne skontaktowanie się z nami oraz usunięcie wiadomości z Państwa komputera.  

This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail by mistake) please notify the sender immediately and destroy this email. Any unauthorized copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

**Comment by DanielRuf** [comment]
@sosoba was this email reply by accident? I just understand English.

**Comment by igor-savin-ht** [comment]
@DanielRuf It looks to be an autoresponder from an email client, probably reacted to notification sent by github.

**Comment by cjbj** [comment]
Appreciating all you eager early-adopters, here's the status:

- we will spend our effort getting the next set of new features ready for a node-oracle 2.3 release (with Node 10 binaries) in the next few weeks (don't hold me to that schedule).  I'll start pushing our current changes to GitHub next week so you have access to the source code and other changes.  There are no plans for pre-built 2.2 binaries.

- @sosoba 404's doesn't lead to compiling because no-one has added "if can't download, then fallback to compile" support.  Lightweight PRs (ie not using node-pre-gyp) are welcome.  Instead, use one of the well [documented methods for installing from source code](https://oracle.github.io/node-oracledb/INSTALL.html#github).

**Comment by cjbj** [comment]
The master branch has the current work-in-progress node-oracledb 2.3.0-dev code & doc with the [various updates](https://github.com/oracle/node-oracledb/blob/master/CHANGELOG.md) we've made for building and running with Node 10.  Please compile & test and let us know what you find.

If you are still using node-oracledb 2.2, please use the user doc on https://oracle.github.io/node-oracledb/doc/api.html instead of in this GitHub repo.

Reminder: I'm not planning on creating binaries until we leave the dev cycle.  We are currently working on Continuous Query Notification support; when that lands we'll do a 2.3.0 production release.

**Comment by cjbj** [comment]
Node-oracledb 2.3 is available on npm with Node.js 10 binaries: https://blogs.oracle.com/opal/node-oracledb-23-with-continuous-query-notifications-is-on-npm
