### ISSUE TITLE
autoCommit  not working

### ISSUE THREAD

**Issue by alciakng** [oracle/node-oracledb#97]
I read insert2 example and copy & paste to my project.

but {autocommit : true }  not working.
commit not executed.
what's wrong ????

**Comment by cjbj** [comment]
Show us your code.  Note it is autoCommit not autocommit.  I want the devs to give errors for invalid attributes but for the moment, any such attribute gets ignored.

**Comment by alciakng** [comment]
module.exports  = new LocalStrategy({
	            // by default, local strategy uses username and password, we will override with email
	            usernameField : 'email',
	            passwordField : 'password',
	            passReqToCallback : true // allows us to pass back the entire request to the callback
	        },
	        function(req, email, password, done) {
	        	
	        	var select = "select * from MEMBER where email = :email";
	        	var insert = "INSERT INTO MEMBER VALUES (:email,:password,:mileage,:class)";
	        	
	        	db.getConnection(
	        			function(err,connection){
	        				 if (err) {
	        				      console.error(err.message);
	        				      return;
	        				 }
	        				 connection.execute(select,[email],{outFormat: oracledb.OBJECT},
	        					function(err,user){
	        				    	console.log(user);
	        						if(err){
	        				
	        							return done(err,req.flash('signUpMessage','인터넷 연결을 확인하세요'));
	        						}
	        						if(user.rows.length>0){
	        							 
	        							return done(null,null,req.flash('signUpMessage','이미 존재하는 이메일 입니다..'));
	        						}
	        						else{
	        							console.log(req.body);
	        							connection.execute(insert,req.body,function(err,result){
		        							 if(err){
		        								console.log("삽입에러");
		        		        				return done(null,null,req.flash('signUpMessage','db점검 중 입니다..'));
		        		        			 } 
		        							 console.log('여기');
		        							 connection.release(function(err){
		        								 if(err){
		        									 console.log(err.message);
		        									 return;
		        								 }
		        								 return done(null,req.body,req.flash('signUpMessage','회원가입성공'));	
		        							 })
	        								
	        						     })
	        						
	        		        	    	      
	        							};
	        						})
	        						
	        			    	});
	        	          });

autoCommit not working

**Comment by alciakng** [comment]
``` javascript
oracledb.getConnection(dbConfig,
	        			function(err,connection){
	        				 if (err) {
	        				      console.error(err.message);
	        				      return;
	        				 }
	        				 connection.execute(select,[email],{outFormat: oracledb.OBJECT,autoCommit:true},
	        					function(err,user){
	        				    	console.log(user);
	        						if(err){
	        							console.error(err.message);
	        							return done(err,req.flash('signUpMessage','인터넷 연결을 확인하세요'));
	        						}
	        						if(user.rows.length>0){
	        							
	        							return done(null,null,req.flash('signUpMessage','이미 존재하는 이메일 입니다..'));
	        						}
	        						else{
	        							console.log(req.body);
	        							connection.execute(insert,req.body,{autoCommit:true},function(err,result){
		        							 if(err){
		        								console.error(err.message);
		        								console.log("삽입에러");
		        		        				return done(null,null,req.flash('signUpMessage','db점검 중 입니다..'));
		        		        			 } 
		        							 console.log('회원가입성공!');
		        							 connection.release(function(err){
		        								 if(err){
		        									 console.log(err.message);
		        									 return;
		        								 }
		        								 return done(null,req.body,req.flash('signUpMessage','회원가입성공'));	
		        							 })
	        								
	        						     })
	        						
	        		        	    	      
	        							};
	        						})
	        						
	        			    	});
	        	          });
```

**Comment by cjbj** [comment]
Works for me.  Make sure you are using Node 0.5.0 because autoCommit had a different name in earlier versions.

************************************

// issue97.js

var oracledb = require('oracledb');
var dbConfig = require('./dbconfig.js');

/*
drop table member;
create table member (email varchar2(40), password varchar2(40), mileage number, class varchar2(1));
insert into member values ('cjones', 'welcome', 11111, 'B');
commit;
*/

var select = "select * from MEMBER where email = :email";
var insert = "INSERT INTO MEMBER VALUES (:email,:password,:mileage,:class)";

var email = 'frednurk';
var bindVars = ['frednurk', 'welcome', 0, 'E'];

oracledb.getConnection(
  dbConfig,
  function(err,connection){
    if (err) {
      console.error(err.message);
      return;
    }
    connection.execute(
      select,
      [email],
      {outFormat: oracledb.OBJECT, autoCommit:true},
      function(err,user){
        console.log(user);
        if (err) {
          console.error(err.message);
          return done(err,flash('signUpMessage','인터넷 연결을 확인하세요'));
        }
        if (user.rows.length > 0) {
          return done(null,null,flash('signUpMessage','이미 존재하는 이메일 입니다..'));
        } else {
          console.log(bindVars);
          connection.execute(
            insert,
            bindVars,
            {autoCommit:true},
            function(err,result) {
            if (err) {
              console.error(err.message);
              console.log("삽입에러");
              return done(null,null,flash('signUpMessage','db점검 중 입니다..'));
            } 
            console.log('회원가입성공!');
            connection.release(
              function(err) {
                if (err) {
                  console.log(err.message);
                  return;
                }
                return done(null, bindVars, flash('signUpMessage','회원가입성공'));
              });
          });
        };
      });
  });

function done(a,bv, cb)
{
  console.log('in done');
  console.log(bindVars);
}

function flash(f, s)
{
  console.log('in flash');
  console.log(f, s);
}


************************************

cjones@cjones-mac:~/n$ node issue97.js 
{ rows: [],
  outBinds: undefined,
  rowsAffected: undefined,
  metaData: 
   [ { name: 'EMAIL' },
     { name: 'PASSWORD' },
     { name: 'MILEAGE' },
     { name: 'CLASS' } ] }
[ 'frednurk', 'welcome', 0, 'E' ]
회원가입성공!
in flash
signUpMessage 회원가입성공
in done
[ 'frednurk', 'welcome', 0, 'E' ]

************************************

SQL> select * from member;

EMAIL					 PASSWORD				     MILEAGE C
---------------------------------------- ---------------------------------------- ---------- -
frednurk				 welcome					   0 E
cjones					 welcome				       11111 B
